// packages/vue-ui/lib/components/TextInput/TextInput.vue
<script setup lang="ts">
	import { ref, computed, useId } from 'vue';
	import type { HTMLAttributes } from 'vue';
	import { XMarkIcon } from '@heroicons/vue/20/solid';
	import type { CommonFieldProps } from '@components/type';
	import { BaseField } from '@components/BaseField';
	import { IconButton } from '@components/IconButton';

	import '@packages/styles/components/TextInput.css';

	defineOptions({ inheritAttrs: false });

	export interface TextInputProps
		extends CommonFieldProps<string>,
			/* @vue-ignore */ HTMLAttributes {
		dataTestid?: string;
	}

	const props = withDefaults(defineProps<TextInputProps>(), {
		size: 'medium',
		required: false,
		disabled: false,
		clearable: false
	});

	const emit = defineEmits<{
		(e: 'update:modelValue', value: string): void;
	}>();

	const inputId = useId();
	const supportingTextId = useId();

	const internalValue = ref(props.defaultValue ?? '');

	const inputValue = computed(() => props.modelValue ?? internalValue.value);

	const handleInputChanged = (e: InputEvent) => {
		const target = e.target as HTMLInputElement;
		internalValue.value = target.value;
		emit('update:modelValue', target.value);
	};

	const handleClear = () => {
		emit('update:modelValue', '');
		internalValue.value = '';
	};

	const shouldShowClearIcon = computed(
		() => props.clearable && typeof inputValue.value === 'string' && inputValue.value.length > 0
	);
</script>

<template>
	<BaseField
		class="TextInput"
		:label="label"
		:supporting-text="supportingText"
		:status="status"
		:required="required"
		:input-id="inputId"
		:disabled="disabled"
		:supporting-text-id="supportingText ? supportingTextId : undefined"
		:size="size"
		:data-testid="dataTestid"
	>
		<div
			class="BaseField_Field"
			:data-clearable="clearable"
			:data-disabled="disabled"
			:data-required="required"
			:data-status="status"
		>
			<input
				:id="inputId"
				class="TextInput_Input"
				:placeholder="placeholder"
				:disabled="disabled"
				:aria-describedby="supportingText ? supportingTextId : undefined"
				:aria-invalid="status === 'error'"
				:value="inputValue"
				:required="required"
				:readonly="readOnly"
				v-bind="$attrs"
				@input="handleInputChanged"
			/>
			<div class="BaseField_Trailing">
				<IconButton
					v-if="shouldShowClearIcon"
					aria-label="Clear"
					size="medium"
					variant="text"
					color="secondary"
					@click="handleClear"
				>
					<XMarkIcon />
				</IconButton>
			</div>
		</div>
	</BaseField>
</template>

// packages/react-ui/lib/components/TextInput/TextInput.tsx
import { ChangeEvent, HTMLAttributes, JSX, useId, useState } from 'react';

import classNames from 'classnames';

import './TextInput.css';

import BaseField from '@components/BaseField';
import { Cross2Icon } from '@radix-ui/react-icons';
import IconButton from '@components/IconButton';
import { CommonFieldProps } from '@components/type';

export interface TextInputProp extends HTMLAttributes<HTMLInputElement>, CommonFieldProps<string> {
	onValueChange?: (value: string) => void;
	name?: string;
	'data-testId'?: string;
	defaultValue?: string;
}

const TextInput = (props: TextInputProp): JSX.Element => {
	const {
		value: externalValue,
		className,
		status,
		required,
		label,
		supportingText,
		placeholder,
		size,
		disabled,
		clearable,
		'data-testId': dataTestId,
		defaultValue,
		onChange,
		onValueChange,
		...rest
	} = props;

	const inputId = useId();
	const supportingTextId = useId();

	const [internalValue, setInternalValue] = useState(defaultValue);

	const value = externalValue ?? internalValue;

	const handleInputChanged = (e: ChangeEvent<HTMLInputElement>) => {
		if (onChange) onChange(e);
		const value = (e.target as HTMLInputElement).value;
		setInternalValue(value);
		if (onValueChange) onValueChange(value);
	};

	const handleClear = () => {
		setInternalValue('');
		if (onValueChange) onValueChange('');
	};

	const shouldShowClearIcon = clearable && value && value.length > 0;

	return (
		<BaseField
			className={classNames('TextInput', className)}
			label={label}
			supportingText={supportingText}
			status={status}
			required={required}
			inputId={inputId}
			disabled={disabled}
			supportingTextId={supportingText ? supportingTextId : undefined}
			size={size}
			data-testId={dataTestId}
		>
			<div className="BaseField_Field" data-clearable={clearable} aria-disabled={disabled}>
				<input
					className="TextInput_Input"
					id={inputId}
					placeholder={placeholder}
					disabled={disabled}
					aria-disabled={disabled}
					aria-describedby={supportingText ? supportingTextId : undefined}
					defaultValue={defaultValue}
					aria-invalid={status === 'error'}
					value={value}
					required={required}
					onChange={handleInputChanged}
					{...rest}
				/>
				<div className="BaseField_Trailing">
					{shouldShowClearIcon && (
						<IconButton
							aria-label="Clear"
							size="medium"
							variant="text"
							color="secondary"
							onClick={handleClear}
						>
							<Cross2Icon />
						</IconButton>
					)}
				</div>
			</div>
		</BaseField>
	);
};

export default TextInput;
