// packages/vue-ui/lib/components/NumberInput/NumberInput.vue
<script setup lang="ts">
	import { useId } from 'vue';
	import { ChevronUpIcon, ChevronDownIcon } from '@heroicons/vue/20/solid';
	import type { CommonFieldProps } from '@components/type';
	import { BaseField } from '@components/BaseField';
	import {
		NumberInput as ArkNumberInput,
		type NumberInputRootEmits
	} from '@ark-ui/vue/number-input';
	import '@packages/styles/components/NumberInput.css';

	defineOptions({ inheritAttrs: false });

	export interface NumberInputProps extends CommonFieldProps<string> {
		modelValue?: string;
		max?: number;
		min?: number;
		formatOptions?: Intl.NumberFormatOptions;
		step?: number;
		inputMode?: 'decimal' | 'numeric';
		locale?: string;
		dataTestid?: string;
	}

	export type NumberInputEmits = NumberInputRootEmits;

	const props = withDefaults(defineProps<NumberInputProps>(), {
		locale: 'en-US'
	});

	const emit = defineEmits<NumberInputEmits>();

	const internalSupportingTextId = useId();
	const defaultInputId = useId();

	const inputIdToUse = () => props.inputId ?? defaultInputId;
	const supportingTextIdToUse = () => props.supportingTextId ?? internalSupportingTextId;
</script>

<template>
	<ArkNumberInput.Root
		class="NumberInput"
		:default-value="defaultValue"
		:model-value="modelValue"
		:disabled="disabled"
		:required="required"
		:step="step"
		:locale="locale"
		:max="max"
		:min="min"
		:format-options="formatOptions"
		:input-mode="inputMode"
		:data-testid="dataTestid"
		as-child
		@value-change="emit('valueChange', $event)"
		@update:model-value="emit('update:modelValue', $event)"
		@value-invalid="emit('valueInvalid', $event)"
		@focus-change="emit('focusChange', $event)"
	>
		<BaseField
			:disabled="disabled"
			:size="size"
			:required="required"
			:label="label"
			:supporting-text="supportingText"
			:status="status"
			:supporting-text-id="supportingTextIdToUse()"
			:input-id="inputIdToUse()"
			:label-element="ArkNumberInput.Label"
		>
			<ArkNumberInput.Control class="NumberInput_Control BaseField_Field">
				<ArkNumberInput.Input
					:id="inputIdToUse()"
					class="NumberInput_Input"
					:aria-describedby="supportingTextIdToUse()"
					:placeholder="placeholder"
				/>
				<div class="NumberInput_Triggers">
					<ArkNumberInput.IncrementTrigger
						class="NumberInput_IncrementTrigger"
						aria-label="increase value"
					>
						<ChevronUpIcon
							width="15"
							height="15"
						/>
					</ArkNumberInput.IncrementTrigger>
					<ArkNumberInput.DecrementTrigger
						class="NumberInput_DecrementTrigger"
						aria-label="decrease value"
					>
						<ChevronDownIcon
							width="15"
							height="15"
						/>
					</ArkNumberInput.DecrementTrigger>
				</div>
			</ArkNumberInput.Control>
		</BaseField>
	</ArkNumberInput.Root>
</template>

// packages/react-ui/lib/components/NumberInput/NumberInput.tsx
import { NumberInput as ArkNumberInput } from '@ark-ui/react/number-input';
import { ChevronDownIcon, ChevronUpIcon } from '@radix-ui/react-icons';
import { JSX, useId } from 'react';

import { BaseField } from '@components/BaseField';
import { CommonFieldProps } from '@components/type';

import '@packages/styles/components/NumberInput.css';

export interface NumberInputProps extends CommonFieldProps<string> {
	onValueChange?: (value: string) => void;
	max?: number;
	min?: number;
	formatOptions?: Intl.NumberFormatOptions;
	step?: number;
	inputMode?: 'decimal' | 'numeric';
	locale?: string;
	'data-testid'?: string;
}

const NumberInput = (props: NumberInputProps): JSX.Element => {
	const {
		value,
		defaultValue,
		onValueChange,
		disabled,
		size,
		required,
		placeholder,
		label,
		supportingText,
		status,
		step,
		supportingTextId,
		inputId,
		locale = 'en-US',
		'data-testid': dataTestId,
		...rest
	} = props;

	const handleValueChange: ArkNumberInput.RootProps['onValueChange'] = (details) => {
		onValueChange?.(details.value);
	};

	const internalSupportingTextId = useId();

	return (
		<ArkNumberInput.Root
			className="NumberInput"
			defaultValue={defaultValue}
			value={value}
			disabled={disabled}
			required={required}
			step={step}
			locale={locale}
			data-testid={dataTestId}
			onValueChange={handleValueChange}
			asChild
			{...rest}
		>
			<BaseField
				disabled={disabled}
				size={size}
				required={required}
				label={label}
				supportingText={supportingText}
				status={status}
				supportingTextId={supportingTextId ?? internalSupportingTextId}
				inputId={inputId}
				labelElement={ArkNumberInput.Label}
			>
				<ArkNumberInput.Control className="NumberInput_Control BaseField_Field">
					<ArkNumberInput.Input
						className="NumberInput_Input"
						id={inputId}
						aria-describedby={supportingTextId ?? internalSupportingTextId}
						placeholder={placeholder}
					/>
					<div className="NumberInput_Triggers">
						<ArkNumberInput.IncrementTrigger
							className="NumberInput_IncrementTrigger"
							aria-label="increase value"
						>
							<ChevronUpIcon />
						</ArkNumberInput.IncrementTrigger>
						<ArkNumberInput.DecrementTrigger
							className="NumberInput_DecrementTrigger"
							aria-label="decrease value"
						>
							<ChevronDownIcon />
						</ArkNumberInput.DecrementTrigger>
					</div>
				</ArkNumberInput.Control>
			</BaseField>
		</ArkNumberInput.Root>
	);
};

export default NumberInput;
