// packages/react-ui/lib/components/BaseCombobox/BaseComboboxPopup.tsx
import { Combobox as ArkCombobox, useComboboxContext } from '@ark-ui/react/combobox';
import { CheckIcon } from '@radix-ui/react-icons';
import * as React from 'react';

import { SelectItem, VirtualizationConfig } from '@components/type';
import { VirtualList } from '@components/VirtualList';

import type { BaseComboboxProps } from './BaseCombobox.type';

export interface BaseComboboxPopupProps {
	virtualizationConfig?: VirtualizationConfig;
	items: SelectItem[];
	searchValue: string;
	popupMaxHeight?: number;
	menuHeader?: React.ReactNode;
	menuFooter?: React.ReactNode;
	emptyContent?: React.ReactNode;
	itemContent?: BaseComboboxProps['itemContent'];
}

export const BaseComboboxPopup = ({
	virtualizationConfig,
	items,
	searchValue,
	popupMaxHeight = 300,
	menuHeader,
	menuFooter,
	emptyContent,
	itemContent
}: BaseComboboxPopupProps) => {
	const combobox = useComboboxContext();

	const highlightMatchedSearchValue = (itemLabel: string) => {
		if (!searchValue) return itemLabel;
		const Regex = RegExp(`${searchValue}`, 'gi');
		const results: React.ReactNode[] = [];
		let start = 0;
		let match: RegExpExecArray | null;
		while ((match = Regex.exec(itemLabel)) !== null) {
			const noMatchedSegment = (
				<span key={`normal-${start}`}>{itemLabel.slice(start, match.index)}</span>
			);

			start = match.index + match[0].length;

			const matchedSegment = (
				<span className="HighlightedText" key={`matched-${match.index}`}>
					{itemLabel.slice(match.index, start)}
				</span>
			);

			results.push(noMatchedSegment, matchedSegment);
		}

		const remaining =
			start < itemLabel.length ? (
				<span key={`remaining-${start}`}>{itemLabel.slice(start)}</span>
			) : null;

		results.push(remaining);

		return results;
	};

	const renderItem = (item: SelectItem, index: number) => {
		const itemState = combobox.getItemState({ item });
		return (
			<ArkCombobox.Item className="Menu_Item" key={item.value} item={item} aria-label={item.label}>
				{itemContent ? (
					itemContent({
						item,
						itemIndex: index,
						isSelected: itemState.selected,
						isDisabled: itemState.disabled,
						isHighlighted: itemState.highlighted
					})
				) : (
					<>
						<ArkCombobox.ItemText asChild>
							<div>{highlightMatchedSearchValue(item.label)}</div>
						</ArkCombobox.ItemText>
						<ArkCombobox.ItemIndicator className="MenuItem_TrailingIcon">
							<CheckIcon height={16} width={16} />
						</ArkCombobox.ItemIndicator>
					</>
				)}
			</ArkCombobox.Item>
		);
	};

	const emptyItem = items.length === 0 && (
		<ArkCombobox.Item className="Menu_Item" key="empty" item={{} as SelectItem}>
			{emptyContent ?? (
				<ArkCombobox.ItemText asChild>
					<p>No item found</p>
				</ArkCombobox.ItemText>
			)}
		</ArkCombobox.Item>
	);

	return (
		<ArkCombobox.Positioner
			className="Menu_Positioner"
			style={{ zIndex: 'var(--menu-popup-z-index)' }}
		>
			{virtualizationConfig ? (
				<ArkCombobox.Content className="Menu Combobox_Content" asChild>
					<VirtualList
						items={items}
						estimateSize={virtualizationConfig.estimateSize}
						overscan={virtualizationConfig.overscan}
						getItemKey={virtualizationConfig.getItemKey}
						style={{ maxHeight: `${popupMaxHeight}px` }}
						className="overflow-auto"
						onStartReached={virtualizationConfig.onStartReached}
						onEndReached={virtualizationConfig.onEndReached}
						header={menuHeader}
						footer={
							<>
								{emptyItem}
								{menuFooter}
							</>
						}
					>
						{({ index, itemData }) => renderItem(itemData, index)}
					</VirtualList>
				</ArkCombobox.Content>
			) : (
				<ArkCombobox.Content
					className="Menu Combobox_Content"
					style={{ maxHeight: `${popupMaxHeight}px` }}
				>
					{menuHeader}
					{items.map((item, index) => renderItem(item, index))}
					{emptyItem}
					{menuFooter}
				</ArkCombobox.Content>
			)}
		</ArkCombobox.Positioner>
	);
};

// packages/vue-ui/lib/components/BaseCombobox/BaseComboboxPopup.vue
<script setup lang="ts">
	import { Combobox as ArkCombobox } from '@ark-ui/vue/combobox';
	import { CheckIcon } from '@heroicons/vue/20/solid';
	import { VirtualList } from '@components/VirtualList';
	import type { SelectItem } from '@components/type';
	import type { VirtualizationConfig } from './BaseCombobox.type';

	export interface BaseComboboxPopupProps {
		virtualEnabled: boolean;
		virtualConfig: Required<VirtualizationConfig>;
		items: SelectItem[];
		filteredItemsLength: number;
		searchValue: string;
	}

	defineProps<BaseComboboxPopupProps>();

	const findMatchedSegment = (itemLabel: string, searchValue: string) => {
		if (!searchValue) return [{ type: 'normal', value: itemLabel }];
		const Regex = RegExp(`${searchValue}`, 'gi');
		const results: { type: string; value: string }[] = [];
		let start = 0;
		let match: RegExpExecArray | null;
		while ((match = Regex.exec(itemLabel)) !== null) {
			const noMatchedSegment = {
				type: 'normal',
				value: itemLabel.slice(start, match.index)
			};

			start = match.index + match[0].length;

			const matchedSegment = {
				type: 'matched',
				value: itemLabel.slice(match.index, start)
			};

			results.push(noMatchedSegment, matchedSegment);
		}

		const remaining = start < itemLabel.length ? itemLabel.slice(start) : undefined;

		if (remaining) {
			results.push({ type: 'normal', value: remaining });
		}

		return results;
	};
</script>

<template>
	<Teleport to="body">
		<ArkCombobox.Positioner
			class="Menu_Positioner"
			style="z-index: var(--menu-popup-z-index)"
		>
			<template v-if="virtualEnabled">
				<ArkCombobox.Content
					class="Menu Combobox_Content"
					as-child
				>
					<VirtualList
						:items="items"
						:estimate-size="virtualConfig.estimateSize"
						:overscan="virtualConfig.overscan"
						:get-item-key="(index) => items[index]!.value"
						:style="{ maxHeight: `${virtualConfig.viewHeight}px` }"
						class="overflow-auto"
						@start-reached="virtualConfig.onStartReached"
						@end-reached="virtualConfig.onEndReached"
					>
						<template #header>
							<slot name="menuHeader"></slot>
						</template>
						<template #itemContent="{ itemData: item, index }">
							<ArkCombobox.Item
								:key="item.value"
								class="Menu_Item"
								:item="item"
							>
								<slot
									name="itemContent"
									:item="item"
									:item-index="index"
								>
									<ArkCombobox.ItemText>
										<span
											v-for="(segment, segmentIndex) in findMatchedSegment(item.label, searchValue)"
											:key="segmentIndex"
											:class="{
												HighlightedText: segment.type === 'matched'
											}"
										>
											{{ segment.value }}
										</span>
									</ArkCombobox.ItemText>
									<ArkCombobox.ItemIndicator class="MenuItem_TrailingIcon">
										<CheckIcon />
									</ArkCombobox.ItemIndicator>
								</slot>
							</ArkCombobox.Item>
						</template>
						<template #footer>
							<ArkCombobox.Item
								v-if="filteredItemsLength === 0"
								class="Menu_Item"
								:item="{}"
							>
								<slot name="emptyContent">
									<ArkCombobox.ItemText as-child>
										<p>No item found</p>
									</ArkCombobox.ItemText>
								</slot>
							</ArkCombobox.Item>
							<slot name="menuFooter"></slot>
						</template>
					</VirtualList>
				</ArkCombobox.Content>
			</template>
			<template v-else>
				<ArkCombobox.Content class="Menu Combobox_Content">
					<slot name="menuHeader"></slot>
					<ArkCombobox.Item
						v-for="(item, index) in items"
						:key="item.value"
						class="Menu_Item"
						:item="item"
					>
						<slot
							name="itemContent"
							:item="item"
							:item-index="index"
						>
							<ArkCombobox.ItemText>
								<span
									v-for="(segment, segmentIndex) in findMatchedSegment(item.label, searchValue)"
									:key="segmentIndex"
									:class="{
										HighlightedText: segment.type === 'matched'
									}"
								>
									{{ segment.value }}
								</span>
							</ArkCombobox.ItemText>
							<ArkCombobox.ItemIndicator class="MenuItem_TrailingIcon">
								<CheckIcon />
							</ArkCombobox.ItemIndicator>
						</slot>
					</ArkCombobox.Item>

					<ArkCombobox.Item
						v-if="filteredItemsLength === 0"
						class="Menu_Item"
						:item="{}"
					>
						<slot name="emptyContent">
							<ArkCombobox.ItemText as-child>
								<p>No item found</p>
							</ArkCombobox.ItemText>
						</slot>
					</ArkCombobox.Item>
					<slot name="menuFooter"></slot>
				</ArkCombobox.Content>
			</template>
		</ArkCombobox.Positioner>
	</Teleport>
</template>
