// packages/vue-ui/lib/components/PasswordInput/PasswordInput.vue
<script setup lang="ts">
	import { ref, computed, useId, type HTMLAttributes } from 'vue';
	import { PasswordInput as ArkPasswordInput } from '@ark-ui/vue/password-input';
	import { EyeIcon, EyeSlashIcon, XMarkIcon } from '@heroicons/vue/24/solid';
	import type { CommonFieldProps } from '@components/type';
	import { BaseField } from '@components/BaseField';
	import { IconButton } from '@components/IconButton';
	import '@packages/styles/components/PasswordInput.css';

	defineOptions({ inheritAttrs: false });

	export interface PasswordInputProps
		extends CommonFieldProps<string>,
			/* @vue-ignore */ HTMLAttributes {
		modelValue?: string;
		autoComplete?: string;
		modelVisable?: boolean;
		defaultVisible?: boolean;
		dataTestid?: string;
	}

	export type PasswordInputEmits = {
		valueChange: [e: InputEvent];
		'update:modelValue': [value: string];
		'update:modelVisable': [visible: boolean];
	};

	const props = withDefaults(defineProps<PasswordInputProps>(), {
		size: 'medium',
		required: false,
		disabled: false,
		clearable: false,
		modelVisable: undefined
	});

	const emit = defineEmits<PasswordInputEmits>();

	const internalSupportingTextId = useId();

	const supportingTextIdToUse = computed(() => props.supportingTextId ?? internalSupportingTextId);

	const internalValue = ref(props.defaultValue || '');

	const inputValue = computed(() => (props.modelValue ?? internalValue.value) as string);

	const handleValueChange = (e: InputEvent) => {
		const target = e.target as HTMLInputElement;
		const val = target.value;
		internalValue.value = val;
		emit('update:modelValue', val);
		emit('valueChange', e);
	};

	const handleClearClicked = () => {
		internalValue.value = '';
	};

	const handleVisibilityChange = (details: { visible: boolean }) => {
		emit('update:modelVisable', details.visible);
	};

	const shouldShowClearButton = computed(
		() => props.clearable && typeof inputValue.value === 'string' && inputValue.value.length > 0
	);
</script>

<template>
	<ArkPasswordInput.Root
		class="PasswordInput"
		:read-only="readOnly"
		:required="required"
		:visible="modelVisable"
		:disabled="disabled"
		:default-visible="defaultVisible"
		:data-testid="dataTestid"
		:invalid="status === 'error'"
		as-child
		@visibility-change="handleVisibilityChange"
	>
		<BaseField
			class="PasswordInput_BaseField"
			:read-only="readOnly"
			:required="required"
			:disabled="disabled"
			:size="size"
			:status="status"
			:supporting-text="supportingText"
			:supporting-text-id="supportingTextIdToUse"
			:label="label"
			:label-id="labelId"
			:label-element="ArkPasswordInput.Label"
		>
			<ArkPasswordInput.Control class="BaseField_Field PasswordInput_Control">
				<ArkPasswordInput.Input
					class="PasswordInput_Input"
					:name="name"
					:placeholder="placeholder"
					:value="inputValue"
					:default-value="defaultValue"
					:aria-describedby="supportingText ? supportingTextIdToUse : undefined"
					v-bind="$attrs"
					@input="handleValueChange"
				/>
				<div class="BaseField_Trailing">
					<IconButton
						v-if="shouldShowClearButton"
						size="medium"
						variant="text"
						color="secondary"
						aria-label="Clear value"
						@click="handleClearClicked"
					>
						<XMarkIcon
							class="w-4 h-4"
							width="15"
							height="15"
						/>
					</IconButton>

					<ArkPasswordInput.VisibilityTrigger
						class="BaseField_Trailing PasswordInput_ToggleTrigger"
						as-child
					>
						<IconButton
							size="medium"
							variant="text"
							color="secondary"
							aria-label="Toggle password visibility"
						>
							<ArkPasswordInput.Indicator class="PasswordInput_Indicator">
								<template #fallback>
									<EyeSlashIcon class="w-4 h-4" />
								</template>
								<EyeIcon class="w-4 h-4" />
							</ArkPasswordInput.Indicator>
						</IconButton>
					</ArkPasswordInput.VisibilityTrigger>
				</div>
			</ArkPasswordInput.Control>
		</BaseField>
	</ArkPasswordInput.Root>
</template>

// packages/react-ui/lib/components/PasswordInput/PasswordInput.tsx
import { PasswordInput as ArkPasswordInput } from '@ark-ui/react/password-input';
import BaseField from '@components/BaseField';
import { EyeOpenIcon, EyeClosedIcon, Cross2Icon } from '@radix-ui/react-icons';
import { CommonFieldProps } from '@components/type';
import { ChangeEvent, Ref, useId, HTMLAttributes, useState } from 'react';

import '@packages/styles/components/PasswordInput.css';
import IconButton from '@components/IconButton';

export interface PasswordInputProps
	extends Omit<HTMLAttributes<HTMLInputElement>, 'value' | 'defaultValue'>,
		CommonFieldProps<string> {
	onValueChange?: (value: string) => void;
	onVisibilityChange?: (visible: boolean) => void;
	visible?: boolean;
	autoComplete?: ArkPasswordInput.RootProps['autoComplete'];
	defaultVisible?: boolean;
	'data-testid'?: string;
	ref?: Ref<HTMLDivElement>;
	inputRef?: Ref<HTMLInputElement>;
}

const PasswordInput = ({
	value: externalValue,
	readOnly,
	required,
	defaultValue,
	defaultVisible,
	disabled,
	size,
	ref,
	status,
	supportingText,
	placeholder,
	name,
	visible,
	clearable,
	label,
	inputRef,
	labelId,
	inputId,
	'data-testid': dataTestId,
	onValueChange,
	onVisibilityChange,
	...rest
}: PasswordInputProps) => {
	const [internalValue, setInternalValue] = useState(defaultValue);

	const internalSupportingTextId = useId();

	const value = externalValue ?? internalValue;

	const handleValueChange = (e: ChangeEvent<HTMLInputElement>) => {
		setInternalValue(e.target.value);
		if (onValueChange) {
			onValueChange(e.target.value);
		}
	};

	const handleClearClicked = () => {
		setInternalValue('');
		if (onValueChange) {
			onValueChange('');
		}
	};

	const handleVisibilityChange: ArkPasswordInput.RootProps['onVisibilityChange'] = (details) => {
		const { visible } = details;

		if (onVisibilityChange) {
			onVisibilityChange(visible);
		}
	};

	const shouldShowClearButton = clearable && value && value.length > 0;

	return (
		<ArkPasswordInput.Root
			className="PasswordInput"
			readOnly={readOnly}
			required={required}
			visible={visible}
			disabled={disabled}
			defaultVisible={defaultVisible}
			data-testid={dataTestId}
			invalid={status === 'error'}
			onVisibilityChange={handleVisibilityChange}
			asChild
			ref={ref}
		>
			<BaseField
				className="PasswordInput_BaseField"
				readOnly={readOnly}
				required={required}
				disabled={disabled}
				size={size}
				status={status}
				supportingText={supportingText}
				supportingTextId={internalSupportingTextId}
				label={label}
				labelId={labelId}
				inputId={inputId}
				labelElement={ArkPasswordInput.Label}
			>
				<ArkPasswordInput.Control className="BaseField_Field PasswordInput_Control">
					<ArkPasswordInput.Input
						ref={inputRef}
						name={name}
						className="PasswordInput_Input"
						placeholder={placeholder}
						value={value}
						defaultValue={defaultValue}
						aria-describedby={internalSupportingTextId}
						onChange={handleValueChange}
						{...rest}
					/>
					<div className="BaseField_Trailing">
						{shouldShowClearButton && (
							<IconButton
								size="medium"
								variant="text"
								color="secondary"
								aria-label="Clear value"
								onClick={handleClearClicked}
							>
								<Cross2Icon />
							</IconButton>
						)}

						<ArkPasswordInput.VisibilityTrigger
							className="BaseField_Trailing PasswordInput_ToggleTrigger"
							asChild
						>
							<IconButton
								size="medium"
								variant="text"
								color="secondary"
								aria-label="Toggle password visibility"
							>
								<ArkPasswordInput.Indicator
									className="PasswordInput_Indicator"
									fallback={<EyeClosedIcon />}
								>
									<EyeOpenIcon />
								</ArkPasswordInput.Indicator>
							</IconButton>
						</ArkPasswordInput.VisibilityTrigger>
					</div>
				</ArkPasswordInput.Control>
			</BaseField>
		</ArkPasswordInput.Root>
	);
};

export default PasswordInput;
