// packages/vue-ui/lib/components/BaseField/BaseField.vue
<script setup lang="ts">
	import { FieldLabel } from '@components/FieldLabel';
	import { SupportingText } from '@components/SupportingText';

	import type { BaseFieldProps, BaseFieldSlots } from './BaseField.type';

	import '@packages/styles/components/BaseField.css';

	withDefaults(defineProps<BaseFieldProps>(), {
		size: 'medium',
		required: false,
		disabled: false,
		clearable: false,
		labelElement: 'label',
		status: undefined
	});

	defineSlots<BaseFieldSlots>();
</script>

<template>
	<div
		class="BaseField"
		:data-status="status"
		:data-size="size"
		:data-required="required"
		:aria-disabled="disabled"
		:data-clearable="clearable"
		:data-testid="dataTestid"
	>
		<FieldLabel
			:id="labelId"
			class="BaseField_Label"
			:status="status"
			:required="required"
			:type="labelElement"
			:for="inputId"
			:show-label="!!label"
		>
			{{ label }}
		</FieldLabel>
		<slot />
		<SupportingText
			:id="supportingTextId"
			class="BaseField_SupportingText"
			:status="status"
			:show="!!supportingText"
		>
			{{ supportingText }}
		</SupportingText>
	</div>
</template>

// packages/react-ui/lib/components/BaseField/BaseField.tsx
import { FieldLabel, FieldLabelProps } from '@components/FieldLabel';
import { SupportingText } from '@components/SupportingText';
import { CommonFieldProps } from '@components/type';
import classNames from 'classnames';

import '@packages/styles/components/BaseField.css';
import { ComponentPropsWithRef } from 'react';

export interface BaseFieldProps
	extends Omit<ComponentPropsWithRef<'div'>, 'defaultValue'>,
		CommonFieldProps<string> {
	labelElement?: FieldLabelProps['type'];
	labelId?: string;
	inputId?: string;
}

const BaseField = ({
	children,
	className,
	label,
	supportingText,
	status,
	required,
	clearable,
	disabled,
	ref,
	labelId,
	labelElement,
	inputId,
	size = 'medium',
	supportingTextId,
	...rest
}: BaseFieldProps) => {
	return (
		<div
			ref={ref}
			className={classNames('BaseField', className)}
			data-status={status}
			data-size={size}
			data-required={required}
			aria-disabled={disabled}
			data-clearable={clearable}
			{...rest}
		>
			<FieldLabel
				className="BaseField_Label"
				status={status}
				required={required}
				type={labelElement}
				id={labelId}
				htmlFor={inputId}
				showLabel={Boolean(label)}
			>
				{label}
			</FieldLabel>
			{children}
			<SupportingText
				className="BaseField_SupportingText"
				id={supportingTextId}
				status={status}
				show={Boolean(supportingText)}
			>
				{supportingText}
			</SupportingText>
		</div>
	);
};

export default BaseField;
