// packages/react-ui/lib/components/DateRangePicker/DateRangePicker.tsx
import {
	DatePicker as ArkDatePicker,
	parseDate,
	useDatePickerContext
} from '@ark-ui/react/date-picker';
import { Portal } from '@ark-ui/react/portal';
import { CalendarIcon, Cross2Icon } from '@radix-ui/react-icons';
import dayjs from 'dayjs';
import { AriaAttributes, useId } from 'react';

import BaseCalendarView from '@components/BaseCalendarView/BaseCalendarView';
import { BaseField } from '@components/BaseField';
import { IconButton } from '@components/IconButton';
import { CommonFieldProps } from '@components/type';

import '@packages/styles/components/DateRangePicker.css';

export interface DateRangePickerProps
	extends AriaAttributes,
		Pick<ArkDatePicker.RootProps, 'selectionMode' | 'open' | 'onOpenChange' | 'fixedWeeks'>,
		CommonFieldProps<string[] | Date[]> {
	id?: string;
	'data-testid'?: string;
	format?: string;
	// support ISO 8601 date format or Date object
	value?: string[] | Date[];
	// support ISO 8601 date format or Date object
	defaultValue?: string[] | Date[];
	onValueChange?: (value?: string[]) => void;
}

const DateRangePicker = (props: DateRangePickerProps) => {
	const {
		label,
		'aria-label': ariaLabel,
		id,
		inputId,
		value,
		defaultValue,
		open,
		format = 'DD-MM-YYYY',
		disabled,
		supportingText,
		status,
		'data-testid': dataTestId,
		required,
		size,
		clearable,
		onValueChange,
		onOpenChange
	} = props;

	const parsedDateValue = (() => {
		if (value) {
			return value.map((e) => parseDate(e));
		}
	})();

	const parsedDateDefaultValue = (() => {
		if (defaultValue) {
			return defaultValue.map((e) => parseDate(e));
		}
	})();

	const handleDateChange: ArkDatePicker.RootProps['onValueChange'] = (data) => {
		if (onValueChange) {
			const dates = data.value.map((e) => e.toString());
			onValueChange(dates);
		}
	};

	const supportingTextId = useId();

	return (
		<ArkDatePicker.Root
			id={id}
			className="DatePicker"
			selectionMode="range"
			open={open}
			disabled={disabled}
			required={required}
			data-testid={dataTestId}
			value={parsedDateValue}
			defaultValue={parsedDateDefaultValue}
			format={(date, { locale }) => {
				return dayjs(date.toString()).locale(locale).format(format);
			}}
			onValueChange={handleDateChange}
			onOpenChange={onOpenChange}
			asChild
		>
			<BaseField
				label={label}
				supportingText={supportingText}
				supportingTextId={supportingText ? supportingTextId : undefined}
				status={status}
				required={required}
				disabled={disabled}
				clearable={clearable}
				size={size}
				inputId={inputId}
				labelElement={ArkDatePicker.Label}
			>
				<ArkDatePicker.Control
					className="BaseField_Field DateRangePicker_Control"
					aria-label={ariaLabel}
					aria-disabled={disabled}
					aria-describedby={supportingText ? supportingTextId : undefined}
				>
					<div className="DateRangePicker_Input">
						<DateRangeDisplay formatAsStr={format} />
					</div>
					<div className="BaseField_Trailing">
						{clearable && (
							<ArkDatePicker.ClearTrigger asChild>
								<IconButton variant="text" size="medium" color="secondary" aria-label="Clear value">
									<Cross2Icon />
								</IconButton>
							</ArkDatePicker.ClearTrigger>
						)}
						<ArkDatePicker.Trigger asChild>
							<IconButton variant="text" size="medium" color="secondary" aria-label="Open calendar">
								<CalendarIcon />
							</IconButton>
						</ArkDatePicker.Trigger>
					</div>
					<DateRangePickerHiddenInput />
				</ArkDatePicker.Control>
				<Portal>
					<ArkDatePicker.Positioner>
						<ArkDatePicker.Content>
							<BaseCalendarView />
						</ArkDatePicker.Content>
					</ArkDatePicker.Positioner>
				</Portal>
			</BaseField>
		</ArkDatePicker.Root>
	);
};

export default DateRangePicker;

interface DateRangeDisplayProps {
	formatAsStr: string;
}

const DateRangeDisplay = ({ formatAsStr }: DateRangeDisplayProps) => {
	const { valueAsString } = useDatePickerContext();

	const [startDate, endDate] = valueAsString;

	const startDateStr = startDate ?? formatAsStr;
	const endDateStr = endDate ?? formatAsStr;

	return (
		<p className="DateRangePicker_DisplayArea" aria-label="date range display">
			<span data-greyout={!Boolean(startDate)}>{startDateStr}</span>
			<span data-greyout={!Boolean(startDate)}>&mdash;</span>
			<span data-greyout={!Boolean(endDate)}>{endDateStr}</span>
		</p>
	);
};

const DateRangePickerHiddenInput = () => {
	const { value, setValue, getInputProps } = useDatePickerContext();

	const { id } = getInputProps();

	const textValue = value.map((e) => e.toString()).join(',');

	const handleValueChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		const value = e.target.value;

		if (value && value.length > 0) {
			const [startDate, endDate] = value.split(',');

			if (startDate && endDate) {
				setValue([parseDate(startDate), parseDate(endDate)]);
			}
		}
	};

	return <input id={id} hidden onChange={handleValueChange} value={textValue} tabIndex={-1} />;
};

// packages/vue-ui/lib/components/DateRangePicker/DateRangePicker.vue
<script setup lang="ts">
	import { computed, useId, type ComponentInstance, type HTMLAttributes } from 'vue';
	import {
		DatePicker as ArkDatePicker,
		parseDate,
		type DatePickerRootProps
	} from '@ark-ui/vue/date-picker';

	import { BaseCalendarView } from '@components/BaseCalendar';
	import { BaseField } from '@components/BaseField';
	import { IconButton } from '@components/IconButton';
	import type { CommonFieldProps } from '@components/type';
	import { CalendarIcon, XMarkIcon } from '@heroicons/vue/20/solid';

	import '@packages/styles/components/DateRangePicker.css';
	import dayjs from 'dayjs';

	type ArkDatePickerProps = ComponentInstance<typeof ArkDatePicker.Root>['$props'];

	defineOptions({ inheritAttrs: false });

	export interface BaseDateRangePickerProps
		extends Pick<DatePickerRootProps, 'open' | 'min' | 'max' | 'placeholder' | 'readOnly'>,
			CommonFieldProps<Date[]> {
		modelValue?: Date[];
		defaultValue?: Date[];
		locale?: string;
		format?: string;
		id?: string;
		inputId?: string;
		dataTestid?: string;
	}

	export interface DateRangePickerProps
		extends BaseDateRangePickerProps,
			/*@vue-ignore */ HTMLAttributes {}

	export interface DateRangePickerEmits {
		'update:modelValue': [value: Date[]];
		'update:open': [open: boolean];
		valueChange: [value: Date[]];
	}

	const props = withDefaults(defineProps<DateRangePickerProps>(), {
		format: 'DD-MM-YYYY',
		disabled: false,
		required: false,
		clearable: false,
		modelValue: undefined,
		open: undefined
	});

	const emit = defineEmits<DateRangePickerEmits>();

	const supportingTextId = useId();

	const internalModelValue = computed(() => {
		return props.modelValue ? props.modelValue.map((d) => parseDate(d)) : undefined;
	});

	const internalDefaultValue = computed(() => {
		return props.defaultValue ? props.defaultValue.map((d) => parseDate(d)) : undefined;
	});

	const handleDateChange: ArkDatePickerProps['onValueChange'] = (details) => {
		const { value } = details;
		const timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
		const dates = value.map((val) => val.toDate(timeZone));

		emit('update:modelValue', dates);
		emit('valueChange', dates);
	};

	const formatFunc: ArkDatePickerProps['format'] = (date) => {
		const timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
		return dayjs(date.toDate(timeZone)).format(props.format);
	};
</script>

<template>
	<ArkDatePicker.Root
		:id="id"
		class="DatePicker"
		:open="open"
		:model-value="internalModelValue"
		:default-value="internalDefaultValue"
		:selection-mode="'range'"
		:disabled="disabled"
		:min="min"
		:max="max"
		:format="formatFunc"
		:placeholder="placeholder"
		:read-only="readOnly"
		:required="required"
		:data-testid="dataTestid"
		as-child
		@value-change="handleDateChange"
		@update:open="emit('update:open', $event)"
	>
		<BaseField
			:label="label"
			:supporting-text="supportingText"
			:status="status"
			:disabled="disabled"
			:required="required"
			:size="size"
			:input-id="inputId"
			:supporting-text-id="supportingText ? supportingTextId : undefined"
			:label-element="ArkDatePicker.Label"
		>
			<ArkDatePicker.Control
				class="BaseField_Field DateRangePicker_Control"
				:aria-disabled="disabled"
				:aria-describedby="supportingText ? supportingTextId : undefined"
			>
				<div class="DateRangePicker_Input">
					<ArkDatePicker.Context v-slot="context">
						<p
							class="DateRangePicker_DisplayArea"
							aria-label="date range display"
						>
							<span :data-greyout="!Boolean(context.value[0])">{{
								context.valueAsString[0] || format
							}}</span>
							<span :data-greyout="!Boolean(context.value[0])">&mdash;</span>
							<span :data-greyout="!Boolean(context.value[1])">{{
								context.valueAsString[1] || format
							}}</span>
						</p>
					</ArkDatePicker.Context>
				</div>
				<div class="BaseField_Trailing">
					<ArkDatePicker.ClearTrigger
						v-if="clearable"
						as-child
					>
						<IconButton
							variant="text"
							size="medium"
							color="secondary"
							aria-label="Clear value"
						>
							<slot name="clearIcon">
								<XMarkIcon />
							</slot>
						</IconButton>
					</ArkDatePicker.ClearTrigger>

					<ArkDatePicker.Trigger as-child>
						<IconButton
							variant="text"
							size="medium"
							color="secondary"
							aria-label="Open calendar"
						>
							<slot name="triggerIcon">
								<CalendarIcon />
							</slot>
						</IconButton>
					</ArkDatePicker.Trigger>
				</div>

				<ArkDatePicker.Input
					tabindex="-1"
					style="display: none; user-select: none; pointer-events: none"
					hidden
					:aria-describedby="supportingTextId"
				/>
			</ArkDatePicker.Control>
			<Teleport to="body">
				<ArkDatePicker.Positioner
					class="Menu_Positioner"
					style="z-index: var(--menu-popup-z-index)"
				>
					<ArkDatePicker.Content>
						<BaseCalendarView />
					</ArkDatePicker.Content>
				</ArkDatePicker.Positioner>
			</Teleport>
		</BaseField>
	</ArkDatePicker.Root>
</template>
