// packages/react-ui/lib/components/FieldLabel/FieldLabel.tsx
import classNames from 'classnames';
import { createElement, FunctionComponent, HTMLAttributes, HTMLElementType, JSX } from 'react';

import { FieldStatus } from '@components/type';

import '@packages/styles/components/FieldLabel.css';

export interface FieldLabelProps extends HTMLAttributes<HTMLLabelElement> {
	type?: HTMLElementType | FunctionComponent<Record<string, unknown>>;
	children?: React.ReactNode;
	status?: FieldStatus;
	className?: string;
	required?: boolean;
	htmlFor?: string;
	showLabel?: boolean;
}

const FieldLabel = (props: FieldLabelProps): JSX.Element => {
	const { type = 'label', status, children, className, required, showLabel, ...rest } = props;

	const Component = createElement(
		type,
		{ ...rest, className: classNames('FieldLabel', className), 'data-status': status },
		children
	);

	if (showLabel)
		return (
			<p>
				{Component}
				{required && <span className="FieldLabel_Required">*</span>}
			</p>
		);

	return <></>;
};

export default FieldLabel;

// packages/vue-ui/lib/components/FieldLabel/FieldLabel.vue
<script setup lang="ts">
	import type { LabelHTMLAttributes } from 'vue';
	import type { FieldStatus } from '@components/type';
	import '@packages/styles/components/FieldLabel.css';

	defineOptions({ inheritAttrs: false });

	export interface FieldLabelProps extends /* @vue-ignore */ LabelHTMLAttributes {
		type?: string;
		status?: FieldStatus;
		required?: boolean;
		showLabel?: boolean;
	}

	withDefaults(defineProps<FieldLabelProps>(), {
		type: 'label',
		required: false,
		showLabel: false
	});
</script>

<template>
	<p v-if="showLabel">
		<component
			:is="type"
			class="FieldLabel"
			:data-status="status"
			v-bind="$attrs"
		>
			<slot />
		</component>
		<span
			v-if="required"
			class="FieldLabel_Required"
		>
			*
		</span>
	</p>
</template>
