// packages/vue-ui/lib/components/ToggleButton/ToggleButton.vue
<script setup lang="ts">
	import { ref, computed, type ComponentInstance } from 'vue';
	import { Toggle as ArkToggle, type ToggleRootEmits } from '@ark-ui/vue/toggle';
	import { Button, type ButtonProps } from '@components/Button';

	defineOptions({ inheritAttrs: false });

	export interface ToggleButtonProps extends Omit<ButtonProps, 'variant'> {
		pressed?: boolean;
		defaultPressed?: boolean;
		disabled?: boolean;
	}

	type ArkToggleRootProps = ComponentInstance<typeof ArkToggle.Root>;

	export type ToogleButtonEmits = ToggleRootEmits;

	const props = withDefaults(defineProps<ToggleButtonProps>(), {
		size: 'medium',
		defaultPressed: false,
		pressed: undefined
	});

	const emit = defineEmits<ToogleButtonEmits>();

	const internalPressed = ref(props.defaultPressed);

	const isPressed = computed(() => props.pressed ?? internalPressed.value);

	const handlePressedChange: ArkToggleRootProps['onPressedChange'] = (pressed) => {
		internalPressed.value = pressed;
		emit('update:pressed', pressed);
		emit('pressedChange', pressed);
	};
</script>

<template>
	<ArkToggle.Root
		:pressed="isPressed"
		:default-pressed="defaultPressed"
		:disabled="disabled"
		as-child
		@update:pressed="handlePressedChange"
	>
		<Button
			class="ToggleButton"
			:color="color"
			:size="size"
			:loading="loading"
			:disabled="disabled"
			:type="type"
			:variant="isPressed ? 'contained' : 'outlined'"
			v-bind="$attrs"
		>
			<ArkToggle.Context v-slot="context">
				<slot v-bind="context" />
			</ArkToggle.Context>
		</Button>
	</ArkToggle.Root>
</template>

// packages/react-ui/lib/components/ToggleButton/ToggleButton.tsx
import { Toggle as ArkToggle, UseToggleContext } from '@ark-ui/react/toggle';
import Button, { ButtonProps } from '@components/Button';
import classNames from 'classnames';
import { useState } from 'react';

type ToggleButtonChildren = (
	state: Pick<UseToggleContext, 'pressed' | 'setPressed' | 'disabled'>
) => React.ReactNode;

export interface ToggleButtonProps extends Omit<ButtonProps, 'children' | 'variant'> {
	pressed?: boolean;
	onPressedChange?: (pressed: boolean) => void;
	defaultPressed?: boolean;
	children: ToggleButtonChildren | React.ReactNode;
}

const ToggleButton = ({
	pressed: externalPressed,
	onPressedChange,
	defaultPressed,
	children,
	className,
	size = 'medium',
	color,
	...rest
}: ToggleButtonProps) => {
	const [internalpressed, setInternalPressed] = useState(defaultPressed);

	const pressed = externalPressed ?? internalpressed;

	const variant: ButtonProps['variant'] = pressed ? 'contained' : 'outlined';

	const handleOnPressedChange: ArkToggle.RootProps['onPressedChange'] = (pressed) => {
		setInternalPressed(pressed);
		if (onPressedChange) {
			onPressedChange(pressed);
		}
	};

	return (
		<ArkToggle.Root pressed={pressed} onPressedChange={handleOnPressedChange} asChild>
			<Button
				className={classNames('ToggleButton', 'Button', className)}
				color={color}
				size={size}
				variant={variant}
				{...rest}
			>
				<ArkToggle.Context>
					{(context) => {
						const content = typeof children === 'function' ? children(context) : children;
						return content;
					}}
				</ArkToggle.Context>
			</Button>
		</ArkToggle.Root>
	);
};

export default ToggleButton;
