// packages/react-ui/lib/components/DropDownMenu/DropDownMenu.tsx
import { Menu as ArkMenu } from '@ark-ui/react/menu';
import { ItemObject } from '@components/type';
import classNames from 'classnames';
import { JSX } from 'react';
import SubMenu from '@components/SubMenu/SubMenu';
import { Portal } from '@ark-ui/react/portal';
import '@packages/styles/components/DropDownMenu.css';

type StandardItem = ItemObject & {
	type?: never;
};

export interface NestedMenu extends ItemObject {
	type: 'nested';
	items: MenuItem[];
}

export interface GroupItem extends ItemObject {
	type: 'group';
	items: MenuItem[];
}

type MenuItem = StandardItem | NestedMenu | GroupItem;

export interface DropdownMenuProps {
	className?: string;
	items?: MenuItem[];
	children?: React.ReactNode;
	CustomTrigger?: React.ReactNode;
	CustomItem?: (item: ItemObject) => React.ReactNode;
}

const DropDownMenu = (props: DropdownMenuProps): JSX.Element => {
	const { items = [], className, CustomTrigger, children, CustomItem } = props;
	return (
		<ArkMenu.Root>
			<ArkMenu.Trigger className={classNames('Menu_Trigger', className)} asChild={!!CustomTrigger}>
				{CustomTrigger ?? children}
			</ArkMenu.Trigger>
			<Portal>
				<ArkMenu.Positioner>
					<ArkMenu.Content className="Menu">
						{items.map((item) => {
							switch (item.type) {
								case 'nested':
									return <SubMenu {...item} key={item.value} />;
								default:
									return (
										<ArkMenu.Item
											className="Menu_Item"
											disabled={item.disabled}
											value={item.value}
											key={item.value}
										>
											{CustomItem ? CustomItem(item) : item.label}
										</ArkMenu.Item>
									);
							}
						})}
					</ArkMenu.Content>
				</ArkMenu.Positioner>
			</Portal>
		</ArkMenu.Root>
	);
};

export default DropDownMenu;

// packages/vue-ui/lib/components/DropdownMenu/DropdownMenu.vue
<script setup lang="ts">
	import { Menu } from '@ark-ui/vue/menu';
	import SubMenu from './SubMenu.vue';
	import type { DropdownMenuProps } from './DropdownMenu.type';

	import '@packages/styles/components/DropDownMenu.css';

	withDefaults(defineProps<DropdownMenuProps>(), {
		items: () => []
	});
</script>

<template>
	<Menu.Root v-bind="$attrs">
		<Menu.Trigger
			as-child
			class="Menu_Trigger"
			:class="className"
		>
			<slot />
		</Menu.Trigger>
		<Teleport to="body">
			<Menu.Positioner>
				<Menu.Content class="Menu">
					<template
						v-for="item in items"
						:key="item.value"
					>
						<SubMenu
							v-if="item.type === 'nested'"
							v-bind="item"
						/>
						<Menu.Item
							v-else
							class="Menu_Item"
							:disabled="item.disabled"
							:value="item.value"
							:aria-label="item.label"
						>
							<slot
								name="item"
								:item="item"
							>
								{{ item.label }}
							</slot>
						</Menu.Item>
					</template>
				</Menu.Content>
			</Menu.Positioner>
		</Teleport>
	</Menu.Root>
</template>
