// packages/vue-ui/lib/components/MultipleCombobox/MultipleCombobox.vue
<script setup lang="ts">
	import { Combobox as ArkCombobox } from '@ark-ui/vue/combobox';
	import {
		BaseCombobox,
		type BaseComboboxProps,
		type BaseComboboxEmits
	} from '@components/BaseCombobox';
	import { Chip } from '@components/Chip';
	import type { SelectItem } from '@components/type';

	import '@packages/styles/components/MultipleCombobox.css';

	defineOptions({ inheritAttrs: false });

	export interface MultipleComboboxProps
		extends Omit<BaseComboboxProps, 'modelValue' | 'defaultValue' | 'multiple'> {
		modelValue?: string[];
		defaultValue?: string[];
		placeholder?: string;
	}

	export type MultipleComboboxEmits = BaseComboboxEmits;

	const props = withDefaults(defineProps<MultipleComboboxProps>(), {
		modelValue: undefined,
		placeholder: undefined,
		items: () => [],
		open: undefined
	});

	const emit = defineEmits<MultipleComboboxEmits>();

	const handleKeydown = (
		e: KeyboardEvent,
		selectedItems: SelectItem[],
		clearValue: (val: string) => void
	) => {
		const { key } = e;
		const target = e.target as HTMLInputElement;

		if (!target.value && key === 'Backspace' && selectedItems.length > 0) {
			const lastSelectedItem = selectedItems[selectedItems.length - 1];
			if (!lastSelectedItem) return;
			clearValue(lastSelectedItem.value);
		}
	};
</script>

<template>
	<BaseCombobox
		class="MultipleCombobox"
		v-bind="props"
		multiple
		@value-change="emit('valueChange', $event)"
		@update:model-value="emit('update:modelValue', $event)"
		@update:open="emit('update:open', $event)"
		@update:input-value="emit('update:inputValue', $event)"
	>
		<template #customValueText="{ supportingTextId }">
			<ArkCombobox.Context v-slot="combobox">
				<div class="MultipleCombobox_DisplayArea">
					<Chip
						v-for="item in combobox.selectedItems"
						:key="item.value"
						:label="item.label"
						removable
						@remove="
							() => {
								combobox.clearValue(item.value);
								combobox.focus();
							}
						"
					/>
					<ArkCombobox.Input
						class="MultipleCombobox_Input"
						:disabled="disabled"
						:placeholder="
							placeholder && combobox.selectedItems.length === 0 ? placeholder : undefined
						"
						:aria-describedby="supportingTextId"
						v-bind="$attrs"
						@keydown="handleKeydown($event, combobox.selectedItems, combobox.clearValue)"
					/>
				</div>
			</ArkCombobox.Context>
		</template>

		<template
			v-for="(_, name) in $slots"
			#[name]="slotProps"
		>
			<slot
				v-if="name !== 'customValueText'"
				:name="name"
				v-bind="slotProps || {}"
			></slot>
		</template>
	</BaseCombobox>
</template>

// packages/react-ui/lib/components/MultipleCombobox/MultipleCombobox.tsx
import { Combobox, useComboboxContext, UseComboboxContext } from '@ark-ui/react/combobox';
import { BaseComboboxProps, BaseCombobox } from '@components/BaseCombobox';
import { JSX, Ref } from 'react';

import { Chip } from '@components/Chip';
import { SelectItem } from '@components/type';
import classNames from 'classnames';

import '@packages/styles/components/MultipleCombobox.css';

export interface MultipleComboboxProps
	extends Omit<BaseComboboxProps, 'value' | 'onValueChange' | 'multiple' | 'defaultValue'> {
	value?: string[];
	defaultValue?: string[];
	onValueChange?: (value: string[], item?: SelectItem[]) => void;
}

const MultipleCombobox = (props: MultipleComboboxProps): JSX.Element => {
	const { value, defaultValue, onValueChange, placeholder, inputRef, className, ...rest } = props;

	const handleValueChange: BaseComboboxProps['onValueChange'] = (data) => {
		if (onValueChange) onValueChange(data.value, data.items);
	};

	return (
		<BaseCombobox
			{...rest}
			value={value}
			className={classNames('MultipleCombobox', className)}
			onValueChange={handleValueChange}
			multiple
			defaultValue={defaultValue}
			CustomValueText={<MultipleComboboxDisplayValue placeholder={placeholder} ref={inputRef} />}
		/>
	);
};

export default MultipleCombobox;

interface MultipleComboboxDisplayValueProps {
	placeholder?: string;
	ref?: Ref<HTMLInputElement>;
}

const MultipleComboboxDisplayValue = ({ placeholder, ref }: MultipleComboboxDisplayValueProps) => {
	const {
		selectedItems = [],
		clearValue,
		focus
	}: UseComboboxContext<SelectItem> = useComboboxContext();

	const handleKeydown = (e: React.KeyboardEvent<HTMLInputElement>) => {
		const { key } = e;
		const target = e.target as HTMLInputElement;

		if (!target.value && key === 'Backspace') {
			const lastSelectedItem = selectedItems[selectedItems.length - 1];
			clearValue(lastSelectedItem.value);
		}
	};

	const displayedPlaceholder = placeholder && selectedItems.length === 0 ? placeholder : undefined;

	return (
		<div className="MultipleCombobox_DisplayArea">
			{selectedItems.map((item) => (
				<Chip
					label={item.label}
					key={item.value}
					removable
					onRemove={() => {
						clearValue(item.value);
						focus();
					}}
				/>
			))}
			<Combobox.Input
				className="MultipleCombobox_Input"
				onKeyDown={handleKeydown}
				placeholder={displayedPlaceholder}
				ref={ref}
			/>
		</div>
	);
};
