// packages/react-ui/lib/components/BaseCalendarView/BaseCalendarDayView.tsx
import { DatePicker } from '@ark-ui/react/date-picker';
import { ChevronLeftIcon, ChevronRightIcon } from '@radix-ui/react-icons';
import { JSX } from 'react';

import { IconButton } from '@components/IconButton';

const BaseCalendarDayView = (): JSX.Element => {
	return (
		<DatePicker.View view="day" className="CalendarView">
			<DatePicker.Context>
				{(datePicker) => (
					<>
						<DatePicker.ViewControl className="CalendarView_Control">
							<DatePicker.PrevTrigger className="CalendarView_NavTrigger" asChild>
								<IconButton size="large" variant="text" color="secondary">
									<ChevronLeftIcon />
								</IconButton>
							</DatePicker.PrevTrigger>
							<DatePicker.ViewTrigger
								className="CalendarView_ViewTrigger"
								aria-label="Switch to month view"
							>
								<DatePicker.RangeText />
							</DatePicker.ViewTrigger>

							<DatePicker.NextTrigger className="CalendarView_NavTrigger" asChild>
								<IconButton size="large" variant="text" color="secondary">
									<ChevronRightIcon />
								</IconButton>
							</DatePicker.NextTrigger>
						</DatePicker.ViewControl>

						<DatePicker.Table className="CalendarView_Table" columns={7}>
							<DatePicker.TableHead className="Calendar_Header">
								<DatePicker.TableRow>
									{datePicker.weekDays.map((weekDay, id) => (
										<DatePicker.TableHeader key={id} className="CalendarView_HeadCol">
											{weekDay.short}
										</DatePicker.TableHeader>
									))}
								</DatePicker.TableRow>
							</DatePicker.TableHead>
							<DatePicker.TableBody className="Calendar_Body">
								{datePicker.weeks.map((week, weekId) => (
									<DatePicker.TableRow key={weekId}>
										{week.map((day, dayId) => (
											<DatePicker.TableCell
												key={dayId}
												value={day}
												className="CalendarView_TableCell"
											>
												<DatePicker.TableCellTrigger className="CalendarView_TableCellTrigger">
													{day.day}
												</DatePicker.TableCellTrigger>
											</DatePicker.TableCell>
										))}
									</DatePicker.TableRow>
								))}
							</DatePicker.TableBody>
						</DatePicker.Table>
					</>
				)}
			</DatePicker.Context>
		</DatePicker.View>
	);
};

export default BaseCalendarDayView;

// packages/vue-ui/lib/components/BaseCalendar/BaseCalendarDayView.vue
<script setup lang="ts">
	import { DatePicker as ArkDatePicker } from '@ark-ui/vue/date-picker';
	import { ChevronLeftIcon, ChevronRightIcon } from '@heroicons/vue/20/solid';
	import { IconButton } from '@components/IconButton';
</script>

<template>
	<ArkDatePicker.View
		view="day"
		class="CalendarView"
	>
		<ArkDatePicker.Context v-slot="datePicker">
			<ArkDatePicker.ViewControl class="CalendarView_Control">
				<ArkDatePicker.PrevTrigger
					class="CalendarView_NavTrigger"
					as-child
				>
					<IconButton
						size="large"
						variant="text"
						color="secondary"
					>
						<ChevronLeftIcon />
					</IconButton>
				</ArkDatePicker.PrevTrigger>
				<ArkDatePicker.ViewTrigger
					class="CalendarView_ViewTrigger"
					aria-label="Switch to month view"
				>
					<ArkDatePicker.RangeText />
				</ArkDatePicker.ViewTrigger>

				<ArkDatePicker.NextTrigger
					class="CalendarView_NavTrigger"
					as-child
				>
					<IconButton
						size="large"
						variant="text"
						color="secondary"
					>
						<ChevronRightIcon />
					</IconButton>
				</ArkDatePicker.NextTrigger>
			</ArkDatePicker.ViewControl>

			<ArkDatePicker.Table
				class="CalendarView_Table"
				:columns="7"
			>
				<ArkDatePicker.TableHead class="Calendar_Header">
					<ArkDatePicker.TableRow>
						<ArkDatePicker.TableHeader
							v-for="(weekDay, id) in datePicker.weekDays"
							:key="id"
							class="CalendarView_HeadCol"
						>
							{{ weekDay.short }}
						</ArkDatePicker.TableHeader>
					</ArkDatePicker.TableRow>
				</ArkDatePicker.TableHead>
				<ArkDatePicker.TableBody class="Calendar_Body">
					<ArkDatePicker.TableRow
						v-for="(week, weekId) in datePicker.weeks"
						:key="weekId"
					>
						<ArkDatePicker.TableCell
							v-for="(day, dayId) in week"
							:key="dayId"
							:value="day"
							class="CalendarView_TableCell"
						>
							<ArkDatePicker.TableCellTrigger class="CalendarView_TableCellTrigger">
								{{ day.day }}
							</ArkDatePicker.TableCellTrigger>
						</ArkDatePicker.TableCell>
					</ArkDatePicker.TableRow>
				</ArkDatePicker.TableBody>
			</ArkDatePicker.Table>
		</ArkDatePicker.Context>
	</ArkDatePicker.View>
</template>
