// packages/react-ui/lib/components/BaseCalendarView/BaseCalendarMonthView.tsx
import { DatePicker } from '@ark-ui/react/date-picker';
import { ChevronLeftIcon, ChevronRightIcon } from '@radix-ui/react-icons';
import IconButton from '@components/IconButton';
import { JSX } from 'react';

const BaseCalendarMonthView = (): JSX.Element => {
	return (
		<DatePicker.View view="month" className="CalendarView">
			<DatePicker.Context>
				{(datePicker) => (
					<>
						<DatePicker.ViewControl className="CalendarView_Control">
							<DatePicker.PrevTrigger className="CalendarView_NavTrigger" asChild>
								<IconButton size="large" variant="text" color="secondary">
									<ChevronLeftIcon />
								</IconButton>
							</DatePicker.PrevTrigger>
							<DatePicker.ViewTrigger
								className="CalendarView_ViewTrigger"
								aria-label="Switch to year view"
							>
								<DatePicker.RangeText />
							</DatePicker.ViewTrigger>
							<DatePicker.NextTrigger className="CalendarView_NavTrigger" asChild>
								<IconButton size="large" variant="text" color="secondary">
									<ChevronRightIcon />
								</IconButton>
							</DatePicker.NextTrigger>
						</DatePicker.ViewControl>
						<DatePicker.Table className="CalendarView_Table" columns={4}>
							<DatePicker.TableBody className="Calendar_Body">
								{datePicker.getMonthsGrid({ columns: 4, format: 'short' }).map((months, id) => (
									<DatePicker.TableRow key={id}>
										{months.map((month, monthId) => (
											<DatePicker.TableCell
												key={monthId}
												value={month.value}
												className="CalendarView_TableCell"
											>
												<DatePicker.TableCellTrigger className="CalendarView_TableCellTrigger">
													{month.label}
												</DatePicker.TableCellTrigger>
											</DatePicker.TableCell>
										))}
									</DatePicker.TableRow>
								))}
							</DatePicker.TableBody>
						</DatePicker.Table>
					</>
				)}
			</DatePicker.Context>
		</DatePicker.View>
	);
};

export default BaseCalendarMonthView;

// packages/vue-ui/lib/components/BaseCalendar/BaseCalendarMonthView.vue
<script setup lang="ts">
	import { DatePicker as ArkDatePicker } from '@ark-ui/vue/date-picker';
	import { ChevronLeftIcon, ChevronRightIcon } from '@heroicons/vue/20/solid';
	import { IconButton } from '@components/IconButton';
</script>

<template>
	<ArkDatePicker.View
		view="month"
		class="CalendarView"
	>
		<ArkDatePicker.Context v-slot="context">
			<ArkDatePicker.ViewControl class="CalendarView_Control">
				<ArkDatePicker.PrevTrigger
					class="CalendarView_NavTrigger"
					as-child
				>
					<IconButton
						size="large"
						variant="text"
						color="secondary"
					>
						<ChevronLeftIcon />
					</IconButton>
				</ArkDatePicker.PrevTrigger>
				<ArkDatePicker.ViewTrigger
					class="CalendarView_ViewTrigger"
					aria-label="Switch to year view"
				>
					<ArkDatePicker.RangeText />
				</ArkDatePicker.ViewTrigger>
				<ArkDatePicker.NextTrigger
					class="CalendarView_NavTrigger"
					as-child
				>
					<IconButton
						size="large"
						variant="text"
						color="secondary"
					>
						<ChevronRightIcon />
					</IconButton>
				</ArkDatePicker.NextTrigger>
			</ArkDatePicker.ViewControl>
			<ArkDatePicker.Table class="CalendarView_Table">
				<ArkDatePicker.TableBody class="Calendar_Body">
					<ArkDatePicker.TableRow
						v-for="(months, id) in context.getMonthsGrid({ columns: 4, format: 'short' })"
						:key="id"
					>
						<ArkDatePicker.TableCell
							v-for="(month, monthId) in months"
							:key="monthId"
							:value="month.value"
							class="CalendarView_TableCell"
						>
							<ArkDatePicker.TableCellTrigger class="CalendarView_TableCellTrigger">
								{{ month.label }}
							</ArkDatePicker.TableCellTrigger>
						</ArkDatePicker.TableCell>
					</ArkDatePicker.TableRow>
				</ArkDatePicker.TableBody>
			</ArkDatePicker.Table>
		</ArkDatePicker.Context>
	</ArkDatePicker.View>
</template>
