// packages/react-ui/lib/components/BaseCalendarView/BaseCalendarYearView.tsx
import { DatePicker } from '@ark-ui/react/date-picker';
import { ChevronLeftIcon, ChevronRightIcon } from '@radix-ui/react-icons';
import IconButton from '@components/IconButton';
import { JSX } from 'react';

const BaseCalendarYearView = (): JSX.Element => {
	return (
		<DatePicker.View view="year" className="CalendarView">
			<DatePicker.Context>
				{(datePicker) => (
					<>
						<DatePicker.ViewControl className="CalendarView_Control">
							<DatePicker.PrevTrigger className="CalendarView_NavTrigger" asChild>
								<IconButton size="large" variant="text" color="secondary">
									<ChevronLeftIcon />
								</IconButton>
							</DatePicker.PrevTrigger>
							<DatePicker.RangeText />
							<DatePicker.NextTrigger className="CalendarView_NavTrigger" asChild>
								<IconButton size="large" variant="text" color="secondary">
									<ChevronRightIcon />
								</IconButton>
							</DatePicker.NextTrigger>
						</DatePicker.ViewControl>
						<DatePicker.Table className="CalendarView_Table" columns={4}>
							<DatePicker.TableBody className="Calendar_Body">
								{datePicker.getYearsGrid({ columns: 4 }).map((years, id) => (
									<DatePicker.TableRow key={id}>
										{years.map((year, yearId) => (
											<DatePicker.TableCell
												key={yearId}
												value={year.value}
												className="CalendarView_TableCell"
											>
												<DatePicker.TableCellTrigger className="CalendarView_TableCellTrigger">
													{year.label}
												</DatePicker.TableCellTrigger>
											</DatePicker.TableCell>
										))}
									</DatePicker.TableRow>
								))}
							</DatePicker.TableBody>
						</DatePicker.Table>
					</>
				)}
			</DatePicker.Context>
		</DatePicker.View>
	);
};

export default BaseCalendarYearView;

// packages/vue-ui/lib/components/BaseCalendar/BaseCalendarYearView.vue
<script setup lang="ts">
	import { DatePicker as ArkDatePicker } from '@ark-ui/vue/date-picker';
	import { ChevronLeftIcon, ChevronRightIcon } from '@heroicons/vue/20/solid';
	import { IconButton } from '@components/IconButton';
</script>

<template>
	<ArkDatePicker.View
		view="year"
		class="CalendarView"
	>
		<ArkDatePicker.Context v-slot="context">
			<ArkDatePicker.ViewControl class="CalendarView_Control">
				<ArkDatePicker.PrevTrigger
					class="CalendarView_NavTrigger"
					as-child
				>
					<IconButton
						size="large"
						variant="text"
						color="secondary"
					>
						<ChevronLeftIcon />
					</IconButton>
				</ArkDatePicker.PrevTrigger>
				<ArkDatePicker.RangeText />
				<ArkDatePicker.NextTrigger
					class="CalendarView_NavTrigger"
					as-child
				>
					<IconButton
						size="large"
						variant="text"
						color="secondary"
					>
						<ChevronRightIcon />
					</IconButton>
				</ArkDatePicker.NextTrigger>
			</ArkDatePicker.ViewControl>
			<ArkDatePicker.Table class="CalendarView_Table">
				<ArkDatePicker.TableBody class="Calendar_Body">
					<ArkDatePicker.TableRow
						v-for="(years, id) in context.getYearsGrid({ columns: 4 })"
						:key="id"
					>
						<ArkDatePicker.TableCell
							v-for="(year, yearId) in years"
							:key="yearId"
							:value="year.value"
							class="CalendarView_TableCell"
						>
							<ArkDatePicker.TableCellTrigger class="CalendarView_TableCellTrigger">
								{{ year.label }}
							</ArkDatePicker.TableCellTrigger>
						</ArkDatePicker.TableCell>
					</ArkDatePicker.TableRow>
				</ArkDatePicker.TableBody>
			</ArkDatePicker.Table>
		</ArkDatePicker.Context>
	</ArkDatePicker.View>
</template>
