// packages/vue-ui/lib/components/BaseSelect/BaseSelect.vue
<script setup lang="ts">
	import {
		Select as ArkSelect,
		createListCollection,
		type SelectRootEmits,
		type SelectRootProps
	} from '@ark-ui/vue/select';
	import { BaseField } from '@components/BaseField';
	import { IconButton } from '@components/IconButton';
	import type { CommonFieldProps, SelectItem } from '@components/type';
	import { CheckIcon, ChevronDownIcon, XMarkIcon } from '@heroicons/vue/20/solid';
	import { computed, useId, type SelectHTMLAttributes } from 'vue';

	import '@packages/styles/components/BaseSelect.css';
	import '@packages/styles/components/DropDownMenu.css';

	defineOptions({ inheritAttrs: false });

	type ArkSelectProps = SelectRootProps<SelectItem>;

	export interface SelectBaseProps
		extends CommonFieldProps<string[]>,
			Pick<
				ArkSelectProps,
				| 'loopFocus'
				| 'open'
				| 'defaultOpen'
				| 'multiple'
				| 'deselectable'
				| 'lazyMount'
				| 'unmountOnExit'
				| 'modelValue'
				| 'defaultValue'
				| 'name'
			> {
		class?: string;
		items?: Array<SelectItem>;
		dataTestid?: string;
	}

	export type BaseSelectProps = SelectBaseProps &
		/* @vue-ignore */ Omit<
			SelectHTMLAttributes,
			'value' | 'disabled' | 'required' | 'size' | 'name' | 'multiple'
		>;

	export interface BaseSelectEmits {
		'update:modelValue': SelectRootEmits<SelectItem>['update:modelValue'];
		'update:open': SelectRootEmits<SelectItem>['update:open'];
		focusOutside: SelectRootEmits<SelectItem>['focusOutside'];
		exitComplete: SelectRootEmits<SelectItem>['exitComplete'];
		valueChange: SelectRootEmits<SelectItem>['valueChange'];
	}

	const props = withDefaults(defineProps<BaseSelectProps>(), {
		items: () => [],
		size: 'medium',
		multiple: false,
		loopFocus: false,
		deselectable: false,
		clearable: false,
		disabled: false,
		required: false,
		open: undefined,
		defaultOpen: undefined,
		modelValue: undefined,
		defaultValue: undefined,
		name: undefined
	});

	const emit = defineEmits<BaseSelectEmits>();

	const supportingTextId = useId();

	const collection = computed(() => createListCollection({ items: props.items }));
</script>

<template>
	<ArkSelect.Root
		:class="['Select', props.class]"
		:name="name"
		:collection="collection"
		:disabled="disabled"
		:required="required"
		:deselectable="deselectable"
		:loop-focus="loopFocus"
		:open="open"
		:default-open="defaultOpen"
		:model-value="modelValue"
		:default-value="defaultValue"
		:unmount-on-exit="unmountOnExit"
		:lazy-mount="lazyMount"
		:multiple="multiple"
		:data-testid="dataTestid"
		as-child
		@update:model-value="emit('update:modelValue', $event)"
		@focus-outside="emit('focusOutside', $event)"
		@update:open="emit('update:open', $event)"
		@exit-complete="emit('exitComplete')"
		@value-change="emit('valueChange', $event)"
	>
		<BaseField
			:label="label"
			:supporting-text="supportingText"
			:status="status"
			:size="size"
			:disabled="disabled"
			:required="required"
			:supporting-text-id="supportingTextId"
			:label-element="ArkSelect.Label"
		>
			<ArkSelect.Control
				class="Select_Control BaseField_Field"
				:data-status="status"
			>
				<ArkSelect.Trigger
					class="Select_Trigger"
					:aria-describedby="supportingTextId"
				>
					<slot name="customValueText">
						<ArkSelect.ValueText
							class="Select_Value"
							:placeholder="placeholder"
						/>
					</slot>
				</ArkSelect.Trigger>

				<div class="Select_Trailing">
					<ArkSelect.ClearTrigger
						v-if="clearable"
						class="Select_ClearButton"
						as-child
					>
						<IconButton
							variant="text"
							color="secondary"
							size="medium"
						>
							<XMarkIcon />
						</IconButton>
					</ArkSelect.ClearTrigger>
					<ArkSelect.Indicator
						class="Select_Indicator"
						aria-label="select indicator"
					>
						<ChevronDownIcon
							width="20"
							height="20"
						/>
					</ArkSelect.Indicator>
				</div>

				<ArkSelect.HiddenSelect
					:name="name"
					:aria-describedby="supportingTextId"
					:tabindex="-1"
					v-bind="$attrs"
				/>
			</ArkSelect.Control>
			<Teleport to="body">
				<ArkSelect.Positioner
					class="Positioner"
					style="z-index: var(--menu-popup-z-index)"
				>
					<ArkSelect.Content class="Menu SelectContent">
						<ArkSelect.Item
							v-for="item in collection.items"
							:key="item.value"
							class="Menu_Item SelectItem"
							:item="item"
						>
							<ArkSelect.ItemText>{{ item.label }}</ArkSelect.ItemText>
							<ArkSelect.ItemIndicator class="MenuItem_TrailingIcon">
								<slot name="triggerIcon">
									<CheckIcon />
								</slot>
							</ArkSelect.ItemIndicator>
						</ArkSelect.Item>
					</ArkSelect.Content>
				</ArkSelect.Positioner>
			</Teleport>
		</BaseField>
	</ArkSelect.Root>
</template>

// packages/react-ui/lib/components/BaseSelect/BaseSelect.tsx
import { ComponentPropsWithRef, JSX, Ref, useId } from 'react';

import { Portal } from '@ark-ui/react/portal';
import { Select as ArkSelect, createListCollection } from '@ark-ui/react/select';
import { CommonFieldProps, SelectItem } from '@components/type';
import { CheckIcon, ChevronDownIcon, Cross2Icon } from '@radix-ui/react-icons';
import classNames from 'classnames';

import '@packages/styles/components/DropDownMenu.css';

import '@packages/styles/components/BaseSelect.css';

import BaseField from '@components/BaseField';
import IconButton from '@components/IconButton';

export interface BaseSelectProps
	extends Omit<ComponentPropsWithRef<'div'>, 'defaultValue'>,
		CommonFieldProps<string[]> {
	items?: Array<SelectItem>;
	placeholder?: string;
	ref?: Ref<HTMLDivElement>;
	deselectable?: boolean;
	loopFocus?: boolean;
	name?: string;
	multiple?: boolean;
	CustomValueText?: React.ReactNode;
	onValueChange?: ArkSelect.RootProps<SelectItem>['onValueChange'];
	'data-testId'?: string;
}

const BaseSelect = ({
	items = [],
	status,
	label,
	className,
	ref,
	size,
	placeholder,
	disabled,
	deselectable,
	supportingText,
	loopFocus,
	clearable,
	value,
	required,
	multiple,
	onValueChange,
	CustomValueText,
	name,
	'data-testId': dataTestId,
	defaultValue
}: BaseSelectProps): JSX.Element => {
	const collection = createListCollection({ items });
	const supportingTextId = useId();

	return (
		<ArkSelect.Root
			className={classNames('Select', className)}
			collection={collection}
			disabled={disabled}
			required={required}
			deselectable={deselectable}
			loopFocus={loopFocus}
			value={value}
			multiple={multiple}
			onValueChange={onValueChange}
			name={name}
			ref={ref}
			defaultValue={defaultValue}
			data-testId={dataTestId}
			asChild
		>
			<BaseField
				label={label}
				supportingText={supportingText}
				status={status}
				size={size}
				disabled={disabled}
				required={required}
				labelElement={ArkSelect.Label}
				supportingTextId={supportingTextId}
			>
				<ArkSelect.Control className="Select_Control BaseField_Field" data-status={status}>
					<ArkSelect.Trigger className="Select_Trigger" aria-describedby={supportingTextId}>
						{CustomValueText ?? (
							<ArkSelect.ValueText className="Select_Value" placeholder={placeholder} />
						)}
					</ArkSelect.Trigger>

					<div className="Select_Trailing">
						{clearable && (
							<ArkSelect.ClearTrigger className="Select_ClearButton" asChild>
								<IconButton variant="text" color="secondary" size="medium">
									<Cross2Icon />
								</IconButton>
							</ArkSelect.ClearTrigger>
						)}
						<ArkSelect.Indicator className="Select_Indicator" aria-label="select indicator">
							<ChevronDownIcon width={20} height={20} />
						</ArkSelect.Indicator>
					</div>

					<ArkSelect.HiddenSelect name={name} aria-describedby={supportingTextId} tabIndex={-1} />
				</ArkSelect.Control>
				<Portal>
					<ArkSelect.Positioner
						className="Positioner"
						style={{ zIndex: 'var(--menu-popup-z-index)' }}
					>
						<ArkSelect.Content className="Menu SelectContent">
							{collection.items.map((item) => (
								<ArkSelect.Item className="Menu_Item SelectItem" key={item.value} item={item}>
									<ArkSelect.ItemText>{item.label}</ArkSelect.ItemText>
									<ArkSelect.ItemIndicator className="MenuItem_TrailingIcon">
										<CheckIcon height={16} width={16} />
									</ArkSelect.ItemIndicator>
								</ArkSelect.Item>
							))}
						</ArkSelect.Content>
					</ArkSelect.Positioner>
				</Portal>
			</BaseField>
		</ArkSelect.Root>
	);
};

export default BaseSelect;
