// packages/vue-ui/lib/components/BaseCalendar/BaseCalendarView.vue
<script setup lang="ts">
	import BaseCalendarMonthView from './BaseCalendarMonthView.vue';
	import BaseCalendarDayView from './BaseCalendarDayView.vue';
	import BaseCalendarYearView from './BaseCalendarYearView.vue';

	import './Calendar.css';
	import { useDatePickerContext } from '@ark-ui/vue/date-picker';
	import { computed } from 'vue';

	const context = useDatePickerContext();

	// implement conditional rendering for CalendarView so that only one type of view is displayed at a time
	const view = computed(() => context.value.view);
</script>

<template>
	<BaseCalendarDayView v-if="view === 'day'" />
	<BaseCalendarMonthView v-if="view === 'month'" />
	<BaseCalendarYearView v-if="view === 'year'" />
</template>

// packages/react-ui/lib/components/BaseCalendarView/BaseCalendarView.tsx
import { useDatePickerContext } from '@ark-ui/react/date-picker';
import { JSX } from 'react';

import BaseCalendarDayView from './BaseCalendarDayView';
import BaseCalendarMonthView from './BaseCalendarMonthView';
import BaseCalendarYearView from './BaseCalendarYearView';

import '@packages/styles/components/Calendar.css';

const BaseCalendarView = (): JSX.Element => {
	const context = useDatePickerContext();

	switch (context.view) {
		case 'day':
			return <BaseCalendarDayView />;
		case 'month':
			return <BaseCalendarMonthView />;
		case 'year':
			return <BaseCalendarYearView />;
	}
};

export default BaseCalendarView;
