// packages/vue-ui/lib/components/BaseCombobox/BaseCombobox.vue
<script setup lang="ts">
	import {
		Combobox as ArkCombobox,
		createListCollection,
		type ComboboxRootEmits,
		type ComboboxRootProps
	} from '@ark-ui/vue/combobox';
	import { BaseField } from '@components/BaseField';
	import { IconButton } from '@components/IconButton';
	import type { CommonFieldProps, SelectItem } from '@components/type';
	import { CheckIcon, ChevronDownIcon, XMarkIcon } from '@heroicons/vue/20/solid';
	import { computed, useId, type HTMLAttributes, ref } from 'vue';

	import '@packages/styles/components/BaseCombobox.css';
	import '@packages/styles/components/DropDownMenu.css';

	defineOptions({ inheritAttrs: false });

	type ArkComboboxProps = ComboboxRootProps<SelectItem>;

	export interface ComboboxBaseProps
		extends CommonFieldProps<string[]>,
			Pick<
				ArkComboboxProps,
				'loopFocus' | 'open' | 'multiple' | 'modelValue' | 'defaultValue' | 'defaultOpen'
			> {
		class?: string;
		items?: Array<SelectItem>;
		dataTestid?: string;
	}

	export type BaseComboboxProps = ComboboxBaseProps &
		/* @vue-ignore */
		Omit<HTMLAttributes, 'value' | 'disabled' | 'required' | 'size' | 'multiple'>;

	export interface BaseComboboxEmits {
		focusOutside: ComboboxRootEmits<SelectItem>['focusOutside'];
		exitComplete: ComboboxRootEmits<SelectItem>['exitComplete'];
		valueChange: ComboboxRootEmits<SelectItem>['valueChange'];
		'update:modelValue': ComboboxRootEmits<SelectItem>['update:modelValue'];
		'update:open': ComboboxRootEmits<SelectItem>['update:open'];
		'update:inputValue': ComboboxRootEmits<SelectItem>['update:inputValue'];
	}

	const props = withDefaults(defineProps<BaseComboboxProps>(), {
		items: () => [],
		size: 'medium',
		multiple: false,
		loopFocus: false,
		clearable: false,
		disabled: false,
		required: false,
		modelValue: undefined,
		defaultValue: undefined,
		open: undefined,
		defaultOpen: undefined
	});

	const emit = defineEmits<BaseComboboxEmits>();

	const supportingTextId = useId();
	const searchValue = ref('');

	const filteredItems = computed(() => {
		if (!searchValue.value) return props.items;
		return props.items.filter((item) =>
			item.label.toLowerCase().includes(searchValue.value.toLowerCase())
		);
	});

	const collection = computed(() => createListCollection({ items: filteredItems.value }));

	const findMatchedSegment = (itemLabel: string, searchValue: string) => {
		if (!searchValue) return [{ type: 'normal', value: itemLabel }];
		const Regex = RegExp(`${searchValue}`, 'gi');
		const results: { type: string; value: string }[] = [];
		let start = 0;
		let match: RegExpExecArray | null;
		while ((match = Regex.exec(itemLabel)) !== null) {
			const noMatchedSegment = {
				type: 'normal',
				value: itemLabel.slice(start, match.index)
			};

			start = match.index + match[0].length;

			const matchedSegment = {
				type: 'matched',
				value: itemLabel.slice(match.index, start)
			};

			results.push(noMatchedSegment, matchedSegment);
		}

		const remaining = start < itemLabel.length ? itemLabel.slice(start) : undefined;

		if (remaining) {
			results.push({ type: 'normal', value: remaining });
		}

		return results;
	};
</script>

<template>
	<ArkCombobox.Root
		:class="['Combobox', props.class]"
		:collection="collection"
		:model-value="modelValue"
		:default-value="defaultValue"
		:loop-focus="loopFocus"
		:disabled="disabled"
		:required="required"
		:multiple="multiple"
		:open="open"
		:default-open="defaultOpen"
		:data-testid="dataTestid"
		:data-mode="multiple ? 'multiple' : undefined"
		as-child
		@update:input-value="
			(text) => {
				searchValue = text.trim();
				emit('update:inputValue', text);
			}
		"
		@update:model-value="emit('update:modelValue', $event)"
		@update:open="emit('update:open', $event)"
		@exit-complete="
			() => {
				searchValue = '';
				emit('exitComplete');
			}
		"
		@focus-outside="emit('focusOutside', $event)"
		@value-change="emit('valueChange', $event)"
	>
		<BaseField
			:label="label"
			:supporting-text="supportingText"
			:status="status"
			:size="size"
			:disabled="disabled"
			:required="required"
			:supporting-text-id="supportingText ? supportingTextId : undefined"
			:label-element="ArkCombobox.Label"
		>
			<ArkCombobox.Control
				class="BaseField_Field Combobox_Control"
				:data-status="status"
				:aria-disabled="disabled"
			>
				<slot
					name="customValueText"
					:supporting-text-id="supportingTextId"
				>
					<ArkCombobox.Input
						:aria-describedby="supportingTextId"
						v-bind="$attrs"
						class="Combobox_Input"
						:disabled="disabled"
						:placeholder="placeholder"
					/>
				</slot>

				<ArkCombobox.ClearTrigger
					v-if="clearable"
					class="Combobox_ClearTrigger"
					as-child
					:tabindex="0"
				>
					<IconButton
						variant="text"
						color="secondary"
						size="medium"
					>
						<slot name="clearIcon">
							<XMarkIcon />
						</slot>
					</IconButton>
				</ArkCombobox.ClearTrigger>

				<ArkCombobox.Trigger
					class="Combobox_Trigger"
					aria-label="Trigger popup"
					as-child
				>
					<IconButton
						variant="text"
						color="secondary"
						size="medium"
					>
						<slot name="triggerIcon">
							<ChevronDownIcon class="Combobox_TriggerIcon" />
						</slot>
					</IconButton>
				</ArkCombobox.Trigger>
			</ArkCombobox.Control>

			<Teleport to="body">
				<ArkCombobox.Positioner
					class="Menu_Positioner"
					style="z-index: var(--menu-popup-z-index)"
				>
					<ArkCombobox.Content class="Menu Combobox_Content">
						<slot name="menuHeader"></slot>
						<ArkCombobox.Item
							v-for="(item, index) in collection.items"
							:key="item.value"
							class="Menu_Item"
							:item="item"
						>
							<slot
								name="itemContent"
								:item="item"
								:item-index="index"
							>
								<ArkCombobox.ItemText>
									<span
										v-for="(segment, segmentIndex) in findMatchedSegment(item.label, searchValue)"
										:key="segmentIndex"
										:class="{
											HighlightedText: segment.type === 'matched'
										}"
									>
										{{ segment.value }}
									</span>
								</ArkCombobox.ItemText>
								<ArkCombobox.ItemIndicator class="MenuItem_TrailingIcon">
									<CheckIcon />
								</ArkCombobox.ItemIndicator>
							</slot>
						</ArkCombobox.Item>

						<ArkCombobox.Item
							v-if="filteredItems.length === 0"
							class="Menu_Item"
							:item="{}"
						>
							<slot name="emptyContent">
								<ArkCombobox.ItemText as-child>
									<p>No item found</p>
								</ArkCombobox.ItemText>
							</slot>
						</ArkCombobox.Item>
						<slot name="menuFooter"></slot>
					</ArkCombobox.Content>
				</ArkCombobox.Positioner>
			</Teleport>
		</BaseField>
	</ArkCombobox.Root>
</template>

// packages/react-ui/lib/components/BaseCombobox/BaseComboBox.tsx
import { Combobox, createListCollection } from '@ark-ui/react/combobox';
import { Portal } from '@ark-ui/react/portal';
import { CheckIcon, ChevronDownIcon, Cross2Icon } from '@radix-ui/react-icons';
import classNames from 'classnames';
import { HTMLAttributes, JSX, Ref, useId, useMemo, useState } from 'react';

import { BaseField } from '@components/BaseField';
import { IconButton } from '@components/IconButton';
import { CommonFieldProps, SelectItem } from '@components/type';

import '@packages/styles/components/BaseCombobox.css';
import '@packages/styles/components/DropDownMenu.css';

export interface BaseComboboxProps
	extends Omit<HTMLAttributes<HTMLInputElement>, 'defaultValue'>,
		CommonFieldProps<string[]> {
	items?: Array<SelectItem>;
	ref?: Ref<HTMLDivElement>;
	inputRef?: Ref<HTMLInputElement>;
	loopFocus?: boolean;
	onValueChange?: Combobox.RootProps<SelectItem>['onValueChange'];
	onOpenChange?: Combobox.RootProps<SelectItem>['onOpenChange'];
	multiple?: boolean;
	CustomValueText?: React.ReactNode;
	'data-testid'?: string;
	open?: boolean;
}

const BaseCombobox = (props: BaseComboboxProps): JSX.Element => {
	const {
		label,
		items = [],
		value,
		loopFocus,
		multiple,
		disabled,
		status,
		className,
		supportingText,
		ref,
		required,
		defaultValue,
		inputRef,
		'data-testid': dataTestid,
		CustomValueText,
		open,
		onValueChange,
		onOpenChange,
		size,
		clearable,
		...rest
	} = props;

	const supportingTextId = useId();

	const [searchValue, setSearchValue] = useState('');

	const filteredItems = useMemo(() => {
		if (!searchValue) return items;
		return items.filter(
			(e) => e.label.toLowerCase().includes(searchValue.toLocaleLowerCase()) && !e.disabled
		);
	}, [searchValue, items]);

	const collection = createListCollection({ items: filteredItems });

	const highlightMatchedSearchValue = (itemLabel: string) => {
		if (!searchValue) return itemLabel;
		const Regex = RegExp(`${searchValue}`, 'gi');
		const results: React.ReactNode[] = [];
		let start = 0;
		let match: RegExpExecArray | null;
		while ((match = Regex.exec(itemLabel)) !== null) {
			const noMatchedSegment = <span>{itemLabel.slice(start, match.index)}</span>;

			start = match.index + match[0].length;

			const matchedSegment = (
				<span className="HighlightedText">{itemLabel.slice(match.index, start)}</span>
			);

			results.push(noMatchedSegment, matchedSegment);
		}

		const remaining = start < itemLabel.length ? <span>{itemLabel.slice(start)}</span> : null;

		results.push(remaining);

		return results;
	};

	const renderEmptyItemMessage = () => {
		if (filteredItems.length === 0)
			return (
				<Combobox.Item className="Menu_Item" key={'no item'} item={{}}>
					<Combobox.ItemText asChild>
						<p>No item found</p>
					</Combobox.ItemText>
				</Combobox.Item>
			);
	};

	return (
		<Combobox.Root
			className={classNames('Combobox', className)}
			collection={collection}
			onInputValueChange={(data) => {
				setSearchValue(data.inputValue.trim());
			}}
			value={value}
			onValueChange={onValueChange}
			onOpenChange={onOpenChange}
			loopFocus={loopFocus}
			disabled={disabled}
			required={required}
			multiple={multiple}
			defaultValue={defaultValue}
			onExitComplete={() => setSearchValue('')}
			onFocusOutside={() => setSearchValue('')}
			ref={ref}
			open={open}
			data-testid={dataTestid}
			data-mode={multiple ? 'multiple' : undefined}
			asChild
		>
			<BaseField
				label={label}
				supportingText={supportingText}
				status={status}
				disabled={disabled}
				required={required}
				labelElement={Combobox.Label}
				supportingTextId={supportingText ? supportingTextId : undefined}
				size={size}
			>
				<Combobox.Control
					className="BaseField_Field Combobox_Control"
					data-status={status}
					aria-disabled={disabled}
				>
					{CustomValueText ?? (
						<Combobox.Input
							className="Combobox_Input"
							disabled={disabled}
							ref={inputRef}
							{...rest}
							aria-describedby={supportingTextId}
						/>
					)}
					{clearable && (
						<Combobox.ClearTrigger className="Combobox_ClearTrigger" asChild tabIndex={0}>
							<IconButton size="medium" variant="text" color="secondary">
								<Cross2Icon />
							</IconButton>
						</Combobox.ClearTrigger>
					)}
					<Combobox.Trigger className="Combobox_Trigger" aria-label="Trigger popup" asChild>
						<IconButton size="medium" variant="text" color="secondary">
							<ChevronDownIcon className="Combobox_TriggerIcon" />
						</IconButton>
					</Combobox.Trigger>
				</Combobox.Control>

				<Portal>
					<Combobox.Positioner
						className="Menu_Positioner"
						style={{ zIndex: 'var(--menu-popup-z-index)' }}
					>
						<Combobox.Content className="Menu Combobox_Content">
							{collection.items.map((item) => (
								<Combobox.Item className="Menu_Item" key={item.value} item={item}>
									<Combobox.ItemText asChild>
										<p>{highlightMatchedSearchValue(item.label)}</p>
									</Combobox.ItemText>
									<Combobox.ItemIndicator className="MenuItem_TrailingIcon">
										<CheckIcon height={16} width={16} />
									</Combobox.ItemIndicator>
								</Combobox.Item>
							))}
							{renderEmptyItemMessage()}
						</Combobox.Content>
					</Combobox.Positioner>
				</Portal>
			</BaseField>
		</Combobox.Root>
	);
};

export default BaseCombobox;
