// packages/react-ui/lib/components/VirtualList/VirtualList.tsx
import { useElementSize } from '@reactuses/core';
import { useVirtualizer, type VirtualItem, type VirtualizerOptions } from '@tanstack/react-virtual';
import classNames from 'classnames';
import { type CSSProperties, type Ref, useCallback, useImperativeHandle, useRef } from 'react';

import type {
	ScrollDirection,
	VirtualListProps,
	VirtualListPublicInstance
} from './VirtualList.type';

type VirtualOptions = VirtualizerOptions<HTMLDivElement, Element>;

function VirtualList<TData>(
	props: VirtualListProps<TData> & { ref?: Ref<VirtualListPublicInstance> }
) {
	const {
		className,
		horizontal = false,
		items = [],
		stickyHeader = false,
		initialOffset = 0,
		getItemKey,
		overscan,
		totalCount,
		estimateSize,
		dynamicSize,
		dataTestid,
		children,
		header,
		footer,
		onScrolling,
		onEndReached,
		onStartReached,
		onRangeChanged,
		ref,
		...rest
	} = props;

	const containerRef = useRef<HTMLDivElement>(null);

	const count = totalCount ?? items.length;

	/** Configure Header */
	const headerRef = useRef<HTMLDivElement>(null);

	const [headerWidth, headerHeight] = useElementSize(headerRef);

	const paddingStart = header ? (horizontal ? headerWidth : headerHeight) : 0;
	const scrollPaddingStart = stickyHeader && header ? (horizontal ? headerWidth : headerHeight) : 0;

	const headerStyle = (() => {
		const baseStyle: CSSProperties = stickyHeader
			? {
					position: 'sticky',
					left: 0,
					top: 0,
					zIndex: 10,
					width: 'max-content'
				}
			: {
					position: 'absolute',
					top: 0,
					left: 0
				};

		return horizontal
			? {
					...baseStyle,
					height: '100%'
				}
			: {
					...baseStyle,
					width: '100%'
				};
	})();
	/** End Configure Header */

	/** Configure Footer */
	const footerRef = useRef<HTMLDivElement>(null);
	const [footerWidth, footerHeight] = useElementSize(footerRef);

	const paddingEnd = footer ? (horizontal ? footerWidth : footerHeight) : 0;

	const footerStyle: CSSProperties = {
		position: 'absolute',
		bottom: 0,
		left: 0,
		width: '100%'
	};
	/** End Configure Footer */

	const firstIndexRef = useRef<number>(undefined);
	const lastIndexRef = useRef<number>(undefined);

	const checkIfValueChanged = (newValue: number, oldValue: number | undefined) => {
		if (oldValue === undefined) {
			return true;
		}
		return newValue !== oldValue;
	};

	const handleOnChanged: VirtualOptions['onChange'] = (virtualizer) => {
		const virtualIndexes = virtualizer.getVirtualIndexes();

		const firstIndex = virtualIndexes[0];

		const lastIndex = virtualIndexes[virtualIndexes.length - 1];

		if (checkIfValueChanged(firstIndex, firstIndexRef.current)) {
			firstIndexRef.current = firstIndex;
			if (firstIndex === 0) {
				onStartReached?.();
			}
		}

		if (checkIfValueChanged(lastIndex, lastIndexRef.current)) {
			lastIndexRef.current = lastIndex;
			if (lastIndex === count - 1) {
				onEndReached?.();
			}
		}

		if (firstIndex !== undefined && lastIndex !== undefined) {
			onRangeChanged?.({
				startIndex: firstIndex,
				endIndex: lastIndex
			});
		}

		if (virtualizer.isScrolling) {
			const direction = virtualizer.scrollDirection as ScrollDirection;
			const offset = virtualizer.scrollOffset ?? 0;
			onScrolling?.({ direction, offsetInPixel: offset });
		}
	};

	// eslint-disable-next-line react-hooks/incompatible-library
	const virtualizer = useVirtualizer({
		count,
		horizontal,
		overscan,
		initialOffset,
		paddingStart,
		scrollPaddingStart,
		paddingEnd,
		getScrollElement: () => containerRef.current,
		estimateSize,
		getItemKey,
		onChange: handleOnChanged
	});

	const virtualItems = virtualizer.getVirtualItems();
	const totalSize = virtualizer.getTotalSize();

	const virtualViewStyle: CSSProperties = horizontal
		? {
				height: '100%',
				width: `${totalSize}px`,
				position: 'relative'
			}
		: {
				height: `${totalSize}px`,
				width: '100%',
				position: 'relative'
			};

	const computeItemStyle = useCallback(
		(item: VirtualItem): CSSProperties => {
			return horizontal
				? {
						position: 'absolute',
						top: 0,
						left: 0,
						height: '100%',
						minWidth: `${item.size}px`,
						transform: `translateX(${item.start}px)`
					}
				: {
						position: 'absolute',
						top: 0,
						left: 0,
						minHeight: `${item.size}px`,
						width: '100%',
						transform: `translateY(${item.start}px)`
					};
		},
		[horizontal]
	);

	const scrollToBottom = useCallback(
		(options?: ScrollToOptions) => {
			virtualizer.scrollToOffset(totalSize, options);
		},
		[virtualizer, totalSize]
	);

	useImperativeHandle(
		ref,
		() => ({
			scrollBy: (offset, options) => virtualizer.scrollBy(offset, options),
			scrollToIndex: (index, options) => virtualizer.scrollToIndex(index, options),
			scrollToOffset: (offset, options) => virtualizer.scrollToOffset(offset, options),
			scrollToBottom
		}),
		[virtualizer, scrollToBottom]
	);

	return (
		<div
			{...rest}
			ref={containerRef}
			className={classNames('VirtualList_Root', className)}
			data-testid={dataTestid}
		>
			<div
				className="VirtualList_VirtualView"
				style={virtualViewStyle}
				data-part="virtual-list_virtual-view"
				role="presentation"
			>
				{header && (
					<div
						ref={headerRef}
						style={headerStyle}
						className="VirtualList_Header"
						data-part="virtual-list_header"
					>
						{header}
					</div>
				)}

				{virtualItems.map((item) => (
					<div
						key={String(item.key)}
						ref={(el) => {
							if (dynamicSize && el) {
								virtualizer.measureElement(el);
							}
						}}
						className="VirtualList_Item"
						style={computeItemStyle(item)}
						data-index={item.index}
						data-part="virtual-list_item"
					>
						{children({ index: item.index, itemData: items[item.index] as TData })}
					</div>
				))}

				{footer && (
					<div
						ref={footerRef}
						style={footerStyle}
						className="VirtualList_Footer"
						data-part="virtual-list_footer"
					>
						{footer}
					</div>
				)}
			</div>
		</div>
	);
}

export default VirtualList;

// packages/vue-ui/lib/components/VirtualList/VirtualList.vue
<script setup lang="ts" generic="TData">
	import { useVirtualizer, type VirtualItem, type VirtualizerOptions } from '@tanstack/vue-virtual';
	import type {
		VirtualListEmits,
		VirtualListProps,
		VirtualListSlots,
		ScrollDirection,
		VirtualListPublicInstance
	} from './VirtualList.type';
	import { computed, ref, watchEffect, type CSSProperties } from 'vue';

	import { useElementSize } from '@vueuse/core';

	const props = withDefaults(defineProps<VirtualListProps<TData>>(), {
		horizontal: false,
		items: () => [],
		stickyHeader: false,
		initialOffset: 0
	});

	const slots = defineSlots<VirtualListSlots<TData>>();

	const emit = defineEmits<VirtualListEmits>();

	const containerRef = ref<HTMLDivElement | null>(null);

	const count = computed(() => props.totalCount ?? props.items.length);

	/** Configure Header */
	const headerRef = ref<HTMLDivElement | null>(null);

	const { height: headerHeight, width: headerWidth } = useElementSize(headerRef);

	const paddingStart = computed(() => {
		if ('header' in slots) {
			return props.horizontal ? headerWidth.value : headerHeight.value;
		}
		return 0;
	});

	const scrollPaddingStart = computed(() => {
		if (props.stickyHeader && 'header' in slots) {
			return props.horizontal ? headerWidth.value : headerHeight.value;
		}
		return 0;
	});

	const headerStyle = computed<CSSProperties>(() => {
		const baseStyle: CSSProperties = props.stickyHeader
			? {
					position: 'sticky',
					left: 0,
					top: 0,
					zIndex: 10,
					width: 'max-content'
				}
			: {
					position: 'absolute',
					top: 0,
					left: 0
				};

		return props.horizontal
			? {
					...baseStyle,
					height: '100%'
				}
			: {
					...baseStyle,
					width: '100%'
				};
	});
	/** End Configure Header */

	/** Configure Footer */
	const footerRef = ref<HTMLDivElement | null>(null);

	const { height: footerHeight, width: footerWidth } = useElementSize(footerRef);

	const paddingEnd = computed(() => {
		if ('footer' in slots) {
			return props.horizontal ? footerWidth.value : footerHeight.value;
		}
		return 0;
	});

	const footerStyle = computed<CSSProperties>(() => {
		return {
			position: 'absolute',
			bottom: 0,
			left: 0,
			width: '100%'
		};
	});
	/** End Configure Footer */

	const virtualizerOptions = computed(
		() =>
			({
				count: count.value,
				getScrollElement: () => containerRef.value,
				estimateSize: props.estimateSize,
				horizontal: props.horizontal,
				overscan: props.overscan,
				initialOffset: props.initialOffset,
				paddingStart: paddingStart.value,
				scrollPaddingStart: scrollPaddingStart.value,
				paddingEnd: paddingEnd.value
			}) satisfies Partial<VirtualizerOptions<HTMLDivElement, Element>>
	);

	const virtualizer = useVirtualizer(virtualizerOptions);

	const virtualItems = computed(() => virtualizer.value.getVirtualItems());

	const totalSize = computed(() => virtualizer.value.getTotalSize());

	const virtualIndexes = computed(() => virtualizer.value.getVirtualIndexes());

	const firstIndex = computed(() => virtualIndexes.value[0]);

	watchEffect(() => {
		if (firstIndex.value === 0) {
			emit('startReached');
		}
	});

	const lastIndex = computed(() => virtualIndexes.value[virtualIndexes.value.length - 1]);

	watchEffect(() => {
		if (lastIndex.value === count.value - 1) {
			emit('endReached');
		}
	});

	watchEffect(() => {
		if (firstIndex.value !== undefined && lastIndex.value !== undefined) {
			emit('rangeChanged', {
				startIndex: firstIndex.value,
				endIndex: lastIndex.value
			});
		}
	});

	const virtualViewStyle = computed<CSSProperties>(() => {
		return props.horizontal
			? {
					height: '100%',
					width: `${totalSize.value}px`,
					position: 'relative'
				}
			: {
					height: `${totalSize.value}px`,
					width: '100%',
					position: 'relative'
				};
	});

	const computeItemStyle = (item: VirtualItem): CSSProperties => {
		return props.horizontal
			? {
					position: 'absolute',
					top: 0,
					left: 0,
					height: '100%',
					minWidth: `${item.size}px`,
					transform: `translateX(${item.start}px)`
				}
			: {
					position: 'absolute',
					top: 0,
					left: 0,
					minHeight: `${item.size}px`,
					width: '100%',
					transform: `translateY(${item.start}px)`
				};
	};

	watchEffect(() => {
		if (virtualizer.value.isScrolling) {
			const direction = virtualizer.value.scrollDirection as ScrollDirection;
			const offset = virtualizer.value.scrollOffset ?? 0;
			emit('scrolling', { direction, offsetInPixel: offset });
		}
	});

	const scrollToBottom = (options?: ScrollToOptions) => {
		virtualizer.value.scrollToOffset(totalSize.value, options);
	};

	defineExpose<VirtualListPublicInstance>({
		scrollBy: virtualizer.value.scrollBy,
		scrollToIndex: virtualizer.value.scrollToIndex,
		scrollToOffset: virtualizer.value.scrollToOffset,
		scrollToBottom
	});
</script>

<template>
	<div
		ref="containerRef"
		class="VirtualList_Root"
		:data-testid="dataTestid"
	>
		<div
			class="VirtualList_VirtualView"
			:style="virtualViewStyle"
			data-part="virtual-list_virtual-view"
			role="presentation"
		>
			<div
				v-if="slots.header"
				ref="headerRef"
				:style="headerStyle"
				class="VirtualList_Header"
				data-part="virtual-list_header"
			>
				<slot name="header"></slot>
			</div>

			<template
				v-for="item in virtualItems"
				:key="String(item.key)"
			>
				<div
					:ref="(el) => dynamicSize && virtualizer.measureElement(el as HTMLElement)"
					class="VirtualList_Item"
					:style="computeItemStyle(item)"
					:data-index="item.index"
					data-part="virtual-list_item"
				>
					<slot
						name="itemContent"
						:index="item.index"
						:item-data="items[item.index] as TData"
					></slot>
				</div>
			</template>
			<div
				v-if="slots.footer"
				ref="footerRef"
				:style="footerStyle"
				class="VirtualList_Footer"
				data-part="virtual-list_footer"
			>
				<slot name="footer"></slot>
			</div>
		</div>
	</div>
</template>
